package store

// SOMMAIRE (lire en premier, sauter directement au bon passage)
//
// | Élément       | Résumé                                                          | Ligne |
// |---------------|-----------------------------------------------------------------|-------|
// | Task          | A task as persisted, within the scope of its project              | 46    |
// | Note          | A progress note attached to a task                                | 63    |
// | NewTask       | Insertion data for a task, number already reserved                | 71    |
// | TaskFilter    | Criteria for reading a project's backlog                          | 84    |
// | TaskPatch     | Partial patch of a task: a nil field leaves the value in place    | 96    |
// | Dependency    | A blocking edge as persisted                                      | 120   |
// | NewDependency | Data for opening a blocking edge                                  | 136   |
// | Edge          | An active edge, reduced to its two endpoints                      | 147   |
// | Event         | A journal entry, written in the transaction producing it          | 157   |
// | Store         | Persistence contract of the task feature                          | 174   |
// | store         | Implementation backed by the queries generated by sqlc            | 222   |
// | New           | Creates the task store                                            | 231   |
//
// Fin du sommaire.
// =====================================================================
//
// CONTRACT ONLY — the implementations live in task.go, note.go, dependency.go, event.go and tx.go.

import (
	"context"
	"database/sql"
	"errors"
	"time"

	"github.com/Coddyum/flowlio-agents/internal/database"
	"github.com/google/uuid"
)

// ErrNotFound reports a row that is missing or out of scope — the two cases are deliberately
// indistinguishable. ErrConflict covers constraint violations; ErrCorrupted reports an internal
// inconsistency, which is never the caller's fault.
var (
	ErrNotFound  = errors.New("task store: not found")
	ErrConflict  = errors.New("task store: conflict")
	ErrCorrupted = errors.New("task store: corrupted state")
)

// Task is a task of a project's backlog. TeamID and ProjectID are not decorative: they are the
// scope key carried by every query.
type Task struct {
	ID         uuid.UUID
	TeamID     uuid.UUID
	ProjectID  uuid.UUID
	Number     int64
	Title      string
	Body       string
	Status     string
	Priority   string
	Deadline   *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
	ArchivedAt *time.Time
}

// Note is a progress note. It carries no scope of its own: it is never read other than through its
// task, which carries one.
type Note struct {
	ID        uuid.UUID
	Body      string
	CreatedAt time.Time
}

// NewTask carries the insertion data. Number is already reserved by ClaimNumber, in the same
// transaction as the insert.
type NewTask struct {
	TeamID    uuid.UUID
	ProjectID uuid.UUID
	Number    int64
	Title     string
	Body      string
	Status    string
	Priority  string
	Deadline  *time.Time
}

// TaskFilter describes one read of the backlog. An empty Status means "every status"; archived
// tasks stay excluded unless explicitly asked for.
type TaskFilter struct {
	TeamID          uuid.UUID
	ProjectID       uuid.UUID
	Status          string
	IncludeArchived bool
	Limit           int32
}

// TaskPatch is a partial patch: a nil pointer leaves the field untouched.
//
// ClearDeadline exists because nil already means "do not change" — without that flag, wiping a
// deadline would be impossible to express.
type TaskPatch struct {
	TeamID    uuid.UUID
	ProjectID uuid.UUID
	Number    int64

	Title    *string
	Body     *string
	Status   *string
	Priority *string

	Deadline      *time.Time
	ClearDeadline bool

	// Archive takes the task out of the active backlog, in the SAME write as the rest of the patch.
	// This is not a convenience: kept apart, archiving was a second round trip, and a failure
	// between the two made the agent replay a note it had already written.
	Archive bool
}

// Dependency is a blocking edge: "TaskID is blocked by BlockerTaskID until that one reaches
// UntilStatus".
//
// ProjectID is not decorative: it is the SAME column in both composite foreign keys of the table,
// so the two endpoints cannot live in different projects.
type Dependency struct {
	ID            uuid.UUID
	ProjectID     uuid.UUID
	TaskID        uuid.UUID
	BlockerTaskID uuid.UUID
	UntilStatus   string
	SetBlocked    bool
	CreatedAt     time.Time
	ReleasedAt    *time.Time
}

// NewDependency carries the data for opening an edge.
//
// SetBlocked tells whether THIS edge is what moves the task to `blocked`. It is computed by the
// service at write time — afterwards the information is lost: a task already blocked is
// indistinguishable from a task blocked by the edge just opened.
type NewDependency struct {
	TeamID        uuid.UUID
	ProjectID     uuid.UUID
	TaskID        uuid.UUID
	BlockerTaskID uuid.UUID
	UntilStatus   string
	SetBlocked    bool
}

// Edge is an active edge reduced to its two endpoints. That is all the cycle-detection traversal
// needs — the rest of the row would only cross the network for nothing.
type Edge struct {
	TaskID        uuid.UUID
	BlockerTaskID uuid.UUID
}

// Event is a journal entry.
//
// The task feature carries its own event write rather than borrowing the issue feature's: a module
// never imports another module. Both go through the same generated query, which keeps a single
// definition of the table.
type Event struct {
	TeamID         uuid.UUID
	ProjectID      uuid.UUID
	ActorProjectID uuid.UUID
	Kind           string
	SubjectID      uuid.UUID
}

// Store is the contract consumed by the service.
//
// Every method touching a task takes teamID AND projectID: no unscoped read or write exists in
// this contract, so no caller can forget one.
//
// Edge methods take projectID without teamID when they only reach a task through its identifier:
// that identifier always comes from a read already scoped by team, and the table carries no
// team_id to compare against. This is not a relaxation — it is the same rule applied one layer up,
// where the identifier was born.
type Store interface {
	// WithTx runs fn inside a transaction, on a store that shares it. *sql.DB never travels up to
	// the service: all it ever sees is this interface.
	WithTx(ctx context.Context, fn func(Store) error) error

	// ClaimNumber reserves the project's next readable identifier (CORE-34). The counter is shared
	// with issues: a number never names two objects.
	ClaimNumber(ctx context.Context, teamID, projectID uuid.UUID) (int64, error)

	CreateTask(ctx context.Context, in NewTask) (Task, error)
	TaskByNumber(ctx context.Context, teamID, projectID uuid.UUID, number int64) (Task, error)
	ListTasks(ctx context.Context, filter TaskFilter) ([]Task, error)
	UpdateTask(ctx context.Context, patch TaskPatch) (Task, error)

	AddNote(ctx context.Context, teamID, projectID uuid.UUID, number int64, body string) (Note, error)
	// ListNotes returns the tail of the thread — at most limit notes, in write order — and the total
	// number of notes written. The bound is IN the query: a `[:limit]` in Go would still have
	// pulled the whole thread out of Postgres, which is precisely the cost being refused.
	ListNotes(ctx context.Context, teamID, projectID uuid.UUID, number int64, limit int32) ([]Note, int, error)

	CreateDependency(ctx context.Context, in NewDependency) (Dependency, error)

	// ReleaseBlockerEdges releases the edges a task frees by reaching blockerStatus, and returns the
	// tasks thus freed. force ignores the condition: an ARCHIVED blocker will never reach anything,
	// and leaving its edges in place would manufacture undead tasks.
	ReleaseBlockerEdges(ctx context.Context, projectID, blockerTaskID uuid.UUID, blockerStatus string, force bool) ([]uuid.UUID, error)

	// ReleaseEdge releases ONE named edge and returns the freed task. A missing or already-released
	// edge returns an empty list, not an error: both are the same non-event to the caller.
	ReleaseEdge(ctx context.Context, projectID, taskID, blockerTaskID uuid.UUID) ([]uuid.UUID, error)

	// ClearBlock brings the task back from `blocked` to `todo`, and only if all of its edges are
	// released AND at least one of them had blocked it. All three conditions live in the query, so
	// no caller can forget one. false means "nothing to change", not a failure.
	ClearBlock(ctx context.Context, teamID, projectID, taskID uuid.UUID) (bool, error)

	// ActiveEdges returns the project's unreleased blocking graph, for the cycle-detection
	// traversal. Bounded by nature: those are one repo's blocks in force, not its history.
	ActiveEdges(ctx context.Context, projectID uuid.UUID) ([]Edge, error)

	// AppendEvent writes a journal entry, always in the transaction of whatever produces it: an
	// event written apart could go missing while the edge is released, and the unblocked task would
	// never learn about it — the exact gap this feature fills.
	AppendEvent(ctx context.Context, event Event) error
}

// store backs the contract with the generated queries. db only serves to open a transaction in
// WithTx: no query goes through it directly.
type store struct {
	q  *database.Queries
	db *sql.DB
	// inTx marks a store that already carries a transaction, so that WithTx refuses nesting rather
	// than opening a second one on another connection.
	inTx bool
}

// New creates the task store.
func New(q *database.Queries, db *sql.DB) Store {
	return &store{q: q, db: db}
}
