// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dependencies.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const clearTaskBlock = `-- name: ClearTaskBlock :many
UPDATE tasks t
SET status = 'todo', updated_at = now()
WHERE t.id = $1
  AND t.team_id = $2
  AND t.project_id = $3
  AND t.archived_at IS NULL
  AND t.status = 'blocked'
  AND NOT EXISTS (
      SELECT 1 FROM task_dependencies d
      WHERE d.task_id = t.id AND d.released_at IS NULL
  )
  AND EXISTS (
      SELECT 1 FROM task_dependencies d
      WHERE d.task_id = t.id AND d.set_blocked
  )
RETURNING t.number
`

type ClearTaskBlockParams struct {
	TaskID    uuid.UUID `json:"task_id"`
	TeamID    uuid.UUID `json:"team_id"`
	ProjectID uuid.UUID `json:"project_id"`
}

// ClearTaskBlock ramène une tâche de `blocked` à `todo`, et SEULEMENT si c'est une arête qui l'y
// avait mise.
//
// Les trois conditions sont indissociables et tiennent dans la query pour qu'aucune ne puisse
// être oubliée par un appelant :
//   - status = 'blocked'  : un agent qui a déjà repris la tâche à la main n'est pas écrasé ;
//   - aucune arête active : être libéré par une arête sur trois ne débloque rien ;
//   - au moins un set_blocked : une tâche que l'agent avait bloquée pour une autre raison garde
//     son statut. On notifie, on ne décide pas à sa place.
//
// Zéro ligne rendue est un résultat normal, pas une erreur : c'est le cas « on notifie et on ne
// touche pas au statut ».
func (q *Queries) ClearTaskBlock(ctx context.Context, arg ClearTaskBlockParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, clearTaskBlock, arg.TaskID, arg.TeamID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var number int64
		if err := rows.Scan(&number); err != nil {
			return nil, err
		}
		items = append(items, number)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createTaskDependency = `-- name: CreateTaskDependency :one

INSERT INTO task_dependencies (project_id, task_id, blocker_task_id, until_status, set_blocked)
SELECT t.project_id, t.id, $1, $2::task_status, $3::boolean
FROM tasks t
WHERE t.id = $4
  AND t.team_id = $5
  AND t.project_id = $6
  AND t.archived_at IS NULL
RETURNING id, project_id, task_id, blocker_task_id, until_status, set_blocked, created_at, released_at
`

type CreateTaskDependencyParams struct {
	BlockerTaskID uuid.UUID  `json:"blocker_task_id"`
	UntilStatus   TaskStatus `json:"until_status"`
	SetBlocked    bool       `json:"set_blocked"`
	TaskID        uuid.UUID  `json:"task_id"`
	TeamID        uuid.UUID  `json:"team_id"`
	ProjectID     uuid.UUID  `json:"project_id"`
}

// RÈGLE DE SCOPE DE CE FICHIER : project_id sur toute lecture comme sur toute écriture, et
// team_id partout où une tâche est atteinte par autre chose que son identifiant.
//
// Une arête ne peut pas relier deux projets : les deux clés étrangères composites de
// task_dependencies partagent la MÊME colonne project_id, donc la dépendance inter-repos est
// inexprimable en base, pas seulement refusée par le service (D42). Les prédicats de ce fichier
// ne sont pas cette garantie — ils empêchent d'ATTEINDRE une arête d'un autre projet, ce qui est
// une question différente.
// CreateTaskDependency ouvre une arête « task_id est bloquée par blocker_task_id ».
//
// project_id est lu depuis la tâche bloquée plutôt que fourni : c'est ce qui fait entrer les deux
// extrémités dans la même clé étrangère composite. Un blocker d'un autre projet fait alors
// échouer la contrainte, sans qu'aucun prédicat n'ait à le vérifier.
func (q *Queries) CreateTaskDependency(ctx context.Context, arg CreateTaskDependencyParams) (TaskDependency, error) {
	row := q.db.QueryRowContext(ctx, createTaskDependency,
		arg.BlockerTaskID,
		arg.UntilStatus,
		arg.SetBlocked,
		arg.TaskID,
		arg.TeamID,
		arg.ProjectID,
	)
	var i TaskDependency
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.BlockerTaskID,
		&i.UntilStatus,
		&i.SetBlocked,
		&i.CreatedAt,
		&i.ReleasedAt,
	)
	return i, err
}

const listActiveDependencyEdges = `-- name: ListActiveDependencyEdges :many
SELECT d.task_id, d.blocker_task_id
FROM task_dependencies d
WHERE d.project_id = $1
  AND d.released_at IS NULL
`

type ListActiveDependencyEdgesRow struct {
	TaskID        uuid.UUID `json:"task_id"`
	BlockerTaskID uuid.UUID `json:"blocker_task_id"`
}

// ListActiveDependencyEdges rend le graphe de blocage ACTIF du projet, et sert à une seule chose :
// refuser un cycle avant de l'écrire. A bloque B qui bloque A laisserait les deux `blocked` pour
// toujours, sans que rien ne le dise.
//
// Le graphe entier plutôt qu'un parcours récursif en SQL, pour deux raisons. La première est que
// sqlc ne résout pas les colonnes d'une CTE récursive. La seconde vaut mieux que la première : le
// parcours devient une fonction Go pure, donc prouvable sans Postgres — et « un cycle est refusé »
// est précisément le genre de garantie qu'on veut voir tenir dans un test qui ne dépend de rien.
//
// La taille est bornée par la nature de l'objet : ce sont les blocages NON LIBÉRÉS d'un seul repo,
// pas son historique. Les arêtes libérées sont exclues — elles ne bloquent plus, donc elles ne
// peuvent pas fermer un cycle.
func (q *Queries) ListActiveDependencyEdges(ctx context.Context, projectID uuid.UUID) ([]ListActiveDependencyEdgesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveDependencyEdges, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveDependencyEdgesRow{}
	for rows.Next() {
		var i ListActiveDependencyEdgesRow
		if err := rows.Scan(&i.TaskID, &i.BlockerTaskID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseDependenciesOfBlocker = `-- name: ReleaseDependenciesOfBlocker :many
UPDATE task_dependencies d
SET released_at = now()
WHERE d.blocker_task_id = $1
  AND d.project_id = $2
  AND d.released_at IS NULL
  AND (
        $3::boolean
     OR $4::task_status = 'done'
     OR ($4::task_status = 'in_progress' AND d.until_status = 'in_progress')
  )
RETURNING d.task_id
`

type ReleaseDependenciesOfBlockerParams struct {
	BlockerTaskID uuid.UUID  `json:"blocker_task_id"`
	ProjectID     uuid.UUID  `json:"project_id"`
	Force         bool       `json:"force"`
	BlockerStatus TaskStatus `json:"blocker_status"`
}

// ReleaseDependenciesOfBlocker libère les arêtes qu'une tâche vient de débloquer en changeant de
// statut, et rend les tâches concernées.
//
// « Atteindre » un statut est monotone et non une égalité : une bloquante qui saute de `todo` à
// `done` libère aussi les arêtes qui n'attendaient que `in_progress`. L'égalité stricte
// fabriquerait des arêtes que plus rien ne peut libérer — exactement la tâche morte-vivante que
// cette carte existe pour empêcher.
//
// `force` couvre l'archivage : une bloquante archivée n'atteindra jamais rien, ses arêtes se
// libèrent donc quelle que soit leur condition.
func (q *Queries) ReleaseDependenciesOfBlocker(ctx context.Context, arg ReleaseDependenciesOfBlockerParams) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, releaseDependenciesOfBlocker,
		arg.BlockerTaskID,
		arg.ProjectID,
		arg.Force,
		arg.BlockerStatus,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var task_id uuid.UUID
		if err := rows.Scan(&task_id); err != nil {
			return nil, err
		}
		items = append(items, task_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseDependencyPair = `-- name: ReleaseDependencyPair :many
UPDATE task_dependencies d
SET released_at = now()
WHERE d.task_id = $1
  AND d.blocker_task_id = $2
  AND d.project_id = $3
  AND d.released_at IS NULL
RETURNING d.task_id
`

type ReleaseDependencyPairParams struct {
	TaskID        uuid.UUID `json:"task_id"`
	BlockerTaskID uuid.UUID `json:"blocker_task_id"`
	ProjectID     uuid.UUID `json:"project_id"`
}

// ReleaseDependencyPair libère UNE arête nommée, ce que fait unblock_task.
// Zéro ligne rendue signifie « cette arête n'existe pas, ou elle est déjà libérée » : les deux
// sont le même non-événement pour l'appelant.
func (q *Queries) ReleaseDependencyPair(ctx context.Context, arg ReleaseDependencyPairParams) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, releaseDependencyPair, arg.TaskID, arg.BlockerTaskID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var task_id uuid.UUID
		if err := rows.Scan(&task_id); err != nil {
			return nil, err
		}
		items = append(items, task_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
