// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dependencies.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const clearTaskBlock = `-- name: ClearTaskBlock :many
UPDATE tasks t
SET status = 'todo', updated_at = now()
WHERE t.id = $1
  AND t.team_id = $2
  AND t.project_id = $3
  AND t.archived_at IS NULL
  AND t.status = 'blocked'
  AND NOT EXISTS (
      SELECT 1 FROM task_dependencies d
      WHERE d.task_id = t.id AND d.released_at IS NULL
  )
  AND EXISTS (
      SELECT 1 FROM task_dependencies d
      WHERE d.task_id = t.id AND d.set_blocked
  )
RETURNING t.number
`

type ClearTaskBlockParams struct {
	TaskID    uuid.UUID `json:"task_id"`
	TeamID    uuid.UUID `json:"team_id"`
	ProjectID uuid.UUID `json:"project_id"`
}

// ClearTaskBlock brings a task back from `blocked` to `todo`, and ONLY if an edge is what put it
// there.
//
// The three conditions are inseparable and live in the query so that no caller can forget one:
//   - status = 'blocked'       : an agent that already took the task back by hand is not overwritten;
//   - no active edge left      : being released by one edge out of three unblocks nothing;
//   - at least one set_blocked : a task the agent had blocked for another reason keeps its status.
//     We notify, we do not decide on its behalf.
//
// Zero rows returned is a normal result, not an error: it is the "notify and leave the status
// alone" case.
func (q *Queries) ClearTaskBlock(ctx context.Context, arg ClearTaskBlockParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, clearTaskBlock, arg.TaskID, arg.TeamID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var number int64
		if err := rows.Scan(&number); err != nil {
			return nil, err
		}
		items = append(items, number)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createTaskDependency = `-- name: CreateTaskDependency :one

INSERT INTO task_dependencies (project_id, task_id, blocker_task_id, until_status, set_blocked, origin)
SELECT t.project_id, t.id, $1, $2::task_status, $3::boolean, $4::text
FROM tasks t
WHERE t.id = $5
  AND t.team_id = $6
  AND t.project_id = $7
  AND t.archived_at IS NULL
RETURNING id, project_id, task_id, blocker_task_id, until_status, set_blocked, created_at, released_at, origin
`

type CreateTaskDependencyParams struct {
	BlockerTaskID uuid.UUID  `json:"blocker_task_id"`
	UntilStatus   TaskStatus `json:"until_status"`
	SetBlocked    bool       `json:"set_blocked"`
	Origin        string     `json:"origin"`
	TaskID        uuid.UUID  `json:"task_id"`
	TeamID        uuid.UUID  `json:"team_id"`
	ProjectID     uuid.UUID  `json:"project_id"`
}

// SCOPE RULE OF THIS FILE: project_id on every read as on every write, and team_id everywhere a
// task is reached by anything other than its identifier.
//
// An edge cannot join two projects: both composite foreign keys of task_dependencies share the
// SAME project_id column, so a cross-repo dependency is inexpressible in the database, not merely
// refused by the service (D42). The predicates in this file are not that guarantee — they prevent
// REACHING an edge of another project, which is a different question.
// CreateTaskDependency opens an edge "task_id is blocked by blocker_task_id".
//
// project_id is read from the blocked task rather than supplied: that is what brings both
// endpoints into the same composite foreign key. A blocker from another project then fails the
// constraint, without any predicate having to check for it.
//
// origin records WHICH surface opened the edge, and it is only knowable here: afterwards, an edge
// opened by block_task and one compiled from a `#blocked-by` line of a description are
// indistinguishable. It is what makes a body edit unable to release what an agent decided (D47).
func (q *Queries) CreateTaskDependency(ctx context.Context, arg CreateTaskDependencyParams) (TaskDependency, error) {
	row := q.db.QueryRowContext(ctx, createTaskDependency,
		arg.BlockerTaskID,
		arg.UntilStatus,
		arg.SetBlocked,
		arg.Origin,
		arg.TaskID,
		arg.TeamID,
		arg.ProjectID,
	)
	var i TaskDependency
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.BlockerTaskID,
		&i.UntilStatus,
		&i.SetBlocked,
		&i.CreatedAt,
		&i.ReleasedAt,
		&i.Origin,
	)
	return i, err
}

const listActiveDependencyEdges = `-- name: ListActiveDependencyEdges :many
SELECT d.task_id, d.blocker_task_id
FROM task_dependencies d
WHERE d.project_id = $1
  AND d.released_at IS NULL
`

type ListActiveDependencyEdgesRow struct {
	TaskID        uuid.UUID `json:"task_id"`
	BlockerTaskID uuid.UUID `json:"blocker_task_id"`
}

// ListActiveDependencyEdges returns the project's ACTIVE blocking graph, and serves one purpose
// only: refusing a cycle before writing it. A blocking B blocking A would leave both of them
// `blocked` forever, with nothing saying so.
//
// The whole graph rather than a recursive SQL traversal, for two reasons. The first is that sqlc
// does not resolve the columns of a recursive CTE. The second is worth more than the first: the
// traversal becomes a pure Go function, hence provable without Postgres — and "a cycle is refused"
// is precisely the kind of guarantee one wants to see hold in a test that depends on nothing.
//
// The size is bounded by the nature of the object: those are one repo's UNRELEASED blocks, not its
// history. Released edges are excluded — they no longer block, so they cannot close a cycle.
func (q *Queries) ListActiveDependencyEdges(ctx context.Context, projectID uuid.UUID) ([]ListActiveDependencyEdgesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveDependencyEdges, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveDependencyEdgesRow{}
	for rows.Next() {
		var i ListActiveDependencyEdgesRow
		if err := rows.Scan(&i.TaskID, &i.BlockerTaskID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskActiveDependencies = `-- name: ListTaskActiveDependencies :many
SELECT d.id, d.project_id, d.task_id, d.blocker_task_id, d.until_status, d.set_blocked, d.created_at, d.released_at, d.origin
FROM task_dependencies d
WHERE d.project_id = $1
  AND d.task_id = $2
  AND d.released_at IS NULL
`

type ListTaskActiveDependenciesParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	TaskID    uuid.UUID `json:"task_id"`
}

// ListTaskActiveDependencies returns the active edges of ONE blocked task, whole rows this time.
//
// The graph query above keeps nothing but the endpoints, which is all a cycle traversal needs.
// Compiling a description needs more: a `#blocked-by` line naming a pair that is already blocked
// has to be told apart — does it describe the edge that exists, or contradict it? — and the
// difference is carried by until_status.
func (q *Queries) ListTaskActiveDependencies(ctx context.Context, arg ListTaskActiveDependenciesParams) ([]TaskDependency, error) {
	rows, err := q.db.QueryContext(ctx, listTaskActiveDependencies, arg.ProjectID, arg.TaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDependency{}
	for rows.Next() {
		var i TaskDependency
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskID,
			&i.BlockerTaskID,
			&i.UntilStatus,
			&i.SetBlocked,
			&i.CreatedAt,
			&i.ReleasedAt,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseBodyDependencyPair = `-- name: ReleaseBodyDependencyPair :many
UPDATE task_dependencies d
SET released_at = now()
WHERE d.task_id = $1
  AND d.blocker_task_id = $2
  AND d.project_id = $3
  AND d.released_at IS NULL
  AND d.origin = 'body'
RETURNING d.task_id
`

type ReleaseBodyDependencyPairParams struct {
	TaskID        uuid.UUID `json:"task_id"`
	BlockerTaskID uuid.UUID `json:"blocker_task_id"`
	ProjectID     uuid.UUID `json:"project_id"`
}

// ReleaseBodyDependencyPair releases the edge a `#blocked-by` line had opened, when that line
// disappears from a description.
//
// The origin predicate is the whole point (D47). Without it, deleting a line — or pasting over a
// description that carried one — would lift a block opened by block_task, which nobody editing
// that text ever decided. Zero rows is a nominal case: the pair is either free already, or held by
// an edge this surface does not own.
func (q *Queries) ReleaseBodyDependencyPair(ctx context.Context, arg ReleaseBodyDependencyPairParams) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, releaseBodyDependencyPair, arg.TaskID, arg.BlockerTaskID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var task_id uuid.UUID
		if err := rows.Scan(&task_id); err != nil {
			return nil, err
		}
		items = append(items, task_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseDependenciesOfBlocker = `-- name: ReleaseDependenciesOfBlocker :many
UPDATE task_dependencies d
SET released_at = now()
WHERE d.blocker_task_id = $1
  AND d.project_id = $2
  AND d.released_at IS NULL
  AND (
        $3::boolean
     OR $4::task_status = 'done'
     OR ($4::task_status = 'in_progress' AND d.until_status = 'in_progress')
  )
RETURNING d.task_id
`

type ReleaseDependenciesOfBlockerParams struct {
	BlockerTaskID uuid.UUID  `json:"blocker_task_id"`
	ProjectID     uuid.UUID  `json:"project_id"`
	Force         bool       `json:"force"`
	BlockerStatus TaskStatus `json:"blocker_status"`
}

// ReleaseDependenciesOfBlocker releases the edges a task has just freed by changing status, and
// returns the tasks concerned.
//
// "Reaching" a status is monotone and not an equality: a blocker jumping from `todo` to `done`
// also releases the edges that were only waiting for `in_progress`. Strict equality would
// manufacture edges nothing can ever release — exactly the undead task this feature exists to
// prevent.
//
// `force` covers archiving: an archived blocker will never reach anything, so its edges are
// released whatever their condition.
func (q *Queries) ReleaseDependenciesOfBlocker(ctx context.Context, arg ReleaseDependenciesOfBlockerParams) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, releaseDependenciesOfBlocker,
		arg.BlockerTaskID,
		arg.ProjectID,
		arg.Force,
		arg.BlockerStatus,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var task_id uuid.UUID
		if err := rows.Scan(&task_id); err != nil {
			return nil, err
		}
		items = append(items, task_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseDependencyPair = `-- name: ReleaseDependencyPair :many
UPDATE task_dependencies d
SET released_at = now()
WHERE d.task_id = $1
  AND d.blocker_task_id = $2
  AND d.project_id = $3
  AND d.released_at IS NULL
RETURNING d.task_id
`

type ReleaseDependencyPairParams struct {
	TaskID        uuid.UUID `json:"task_id"`
	BlockerTaskID uuid.UUID `json:"blocker_task_id"`
	ProjectID     uuid.UUID `json:"project_id"`
}

// ReleaseDependencyPair releases ONE named edge, which is what unblock_task does.
// Zero rows returned means "this edge does not exist, or is already released": both are the same
// non-event to the caller.
//
// No origin predicate here, and that is deliberate: unblock_task is an explicit act naming its
// edge, so it lifts whatever opened it. Provenance bounds the surface that writes WITHOUT naming
// an edge — a description patch, below.
func (q *Queries) ReleaseDependencyPair(ctx context.Context, arg ReleaseDependencyPairParams) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, releaseDependencyPair, arg.TaskID, arg.BlockerTaskID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var task_id uuid.UUID
		if err := rows.Scan(&task_id); err != nil {
			return nil, err
		}
		items = append(items, task_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const taskProjectKey = `-- name: TaskProjectKey :one
SELECT key FROM projects WHERE id = $1 AND team_id = $2
`

type TaskProjectKeyParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

// TaskProjectKey resolves the key of the token's project (CORE, FRNT…), needed to read a reference
// a human wrote: `@CORE-34` names a task of THIS project, and any other key has to be refused
// rather than silently read as a local number.
//
// Scoped by team_id like every project read, even though the identifier already comes from the
// token.
func (q *Queries) TaskProjectKey(ctx context.Context, arg TaskProjectKeyParams) (string, error) {
	row := q.db.QueryRowContext(ctx, taskProjectKey, arg.ID, arg.TeamID)
	var key string
	err := row.Scan(&key)
	return key, err
}
