// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inbox.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const advanceInboxCursor = `-- name: AdvanceInboxCursor :exec
INSERT INTO token_cursors (token_id, last_event_id)
VALUES ($1, $2)
ON CONFLICT (token_id) DO UPDATE
SET last_event_id = GREATEST(token_cursors.last_event_id, EXCLUDED.last_event_id),
    updated_at    = now()
`

type AdvanceInboxCursorParams struct {
	TokenID     uuid.UUID `json:"token_id"`
	LastEventID int64     `json:"last_event_id"`
}

// GREATEST empêche le curseur de reculer si deux check_inbox concurrents du même token se
// croisent. Aucune transaction n'est nécessaire : le pire cas est un drapeau `new` perdu.
func (q *Queries) AdvanceInboxCursor(ctx context.Context, arg AdvanceInboxCursorParams) error {
	_, err := q.db.ExecContext(ctx, advanceInboxCursor, arg.TokenID, arg.LastEventID)
	return err
}

const inboxCursor = `-- name: InboxCursor :one

SELECT
    coalesce((SELECT c.last_event_id FROM token_cursors c WHERE c.token_id = $1), 0)::bigint
        AS last_event_id,
    coalesce((SELECT max(e.id) FROM events e
              WHERE e.team_id = $2 AND e.notify_project_id = $3), 0)::bigint
        AS head_event_id
`

type InboxCursorParams struct {
	TokenID   uuid.UUID `json:"token_id"`
	TeamID    uuid.UUID `json:"team_id"`
	ProjectID uuid.UUID `json:"project_id"`
}

type InboxCursorRow struct {
	LastEventID int64 `json:"last_event_id"`
	HeadEventID int64 `json:"head_event_id"`
}

// check_inbox renvoie un ÉTAT COURANT, pas un flux. Aucun seau ne dépend du curseur : le curseur
// ne sert qu'au drapeau `new`. Un événement manqué dégrade un new:true en new:false, jamais une
// ligne en absence de ligne.
//
// Le journal n'est jamais lu par un prédicat propre : il est atteint par EXISTS sur un sujet déjà
// scopé. Il n'existe donc aucune query capable de lire l'activité d'un projet tiers.
// InboxCursor reads the token cursor AND the head of what is addressed to this project, in one call.
// The head is captured BEFORE the buckets are computed: any event created during the call stays `new`
// on the next round.
//
// The head is a PER-PROJECT relevance head, not the team's activity: max(id) among the events whose
// notify_project_id is this project — the ones that should actually wake it. A repo answering an issue
// writes an event addressed to the OTHER party, so its own answer never lifts its own head, and the
// probe stops waking it for its own writes.
func (q *Queries) InboxCursor(ctx context.Context, arg InboxCursorParams) (InboxCursorRow, error) {
	row := q.db.QueryRowContext(ctx, inboxCursor, arg.TokenID, arg.TeamID, arg.ProjectID)
	var i InboxCursorRow
	err := row.Scan(&i.LastEventID, &i.HeadEventID)
	return i, err
}

const inboxProjectKey = `-- name: InboxProjectKey :one
SELECT key FROM projects WHERE id = $1 AND team_id = $2
`

type InboxProjectKeyParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

// InboxProjectKey résout la clé du projet du token, nécessaire pour composer les références
// lisibles (CORE-34) de ses propres tâches et des issues qui lui sont adressées.
// Scopée par team_id comme toute lecture de projet, même si l'identifiant vient déjà du token.
func (q *Queries) InboxProjectKey(ctx context.Context, arg InboxProjectKeyParams) (string, error) {
	row := q.db.QueryRowContext(ctx, inboxProjectKey, arg.ID, arg.TeamID)
	var key string
	err := row.Scan(&key)
	return key, err
}

const listInProgressTasks = `-- name: ListInProgressTasks :many
SELECT t.number, t.title, t.priority, t.updated_at
FROM tasks t
WHERE t.team_id     = $1
  AND t.project_id  = $2
  AND t.status      = 'in_progress'
  AND t.archived_at IS NULL
ORDER BY t.updated_at DESC
LIMIT $3::int
`

type ListInProgressTasksParams struct {
	TeamID    uuid.UUID `json:"team_id"`
	ProjectID uuid.UUID `json:"project_id"`
	MaxRows   int32     `json:"max_rows"`
}

type ListInProgressTasksRow struct {
	Number    int64        `json:"number"`
	Title     string       `json:"title"`
	Priority  TaskPriority `json:"priority"`
	UpdatedAt time.Time    `json:"updated_at"`
}

// Seau 3 — in_progress : une tâche restée là signale une session interrompue, à reprendre avant
// d'en ouvrir une nouvelle. Pas de drapeau `new` : c'est mon propre travail.
func (q *Queries) ListInProgressTasks(ctx context.Context, arg ListInProgressTasksParams) ([]ListInProgressTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, listInProgressTasks, arg.TeamID, arg.ProjectID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInProgressTasksRow{}
	for rows.Next() {
		var i ListInProgressTasksRow
		if err := rows.Scan(
			&i.Number,
			&i.Title,
			&i.Priority,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomingOpenIssues = `-- name: ListIncomingOpenIssues :many
SELECT i.number, i.title, i.updated_at,
       a.key AS peer_key,
       coalesce(left(m.body_md, 500), '')::text AS excerpt,
       coalesce(char_length(m.body_md) > 500, false)::boolean AS truncated,
       EXISTS (
           SELECT 1 FROM events e
           WHERE e.subject_type = 'issue' AND e.subject_id = i.id AND e.id > $1
       ) AS is_new
FROM issues i
JOIN projects a ON a.id = i.author_project_id AND a.team_id = i.team_id
LEFT JOIN LATERAL (
    SELECT im.body_md FROM issue_messages im
    WHERE im.issue_id = i.id
    ORDER BY im.created_at DESC, im.id DESC
    LIMIT 1
) m ON true
WHERE i.team_id    = $2
  AND i.project_id = $3
  AND i.state      = 'open'
ORDER BY i.updated_at DESC
LIMIT $4::int
`

type ListIncomingOpenIssuesParams struct {
	LastEventID int64     `json:"last_event_id"`
	TeamID      uuid.UUID `json:"team_id"`
	ProjectID   uuid.UUID `json:"project_id"`
	MaxRows     int32     `json:"max_rows"`
}

type ListIncomingOpenIssuesRow struct {
	Number    int64     `json:"number"`
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updated_at"`
	PeerKey   string    `json:"peer_key"`
	Excerpt   string    `json:"excerpt"`
	Truncated bool      `json:"truncated"`
	IsNew     bool      `json:"is_new"`
}

// Seau 1 — needs_answer : quelqu'un est bloqué sur moi.
// Dans ce seau, le dernier message est toujours celui de l'auteur : ma propre réponse ferait
// passer l'issue en `answered` et la sortirait du seau.
func (q *Queries) ListIncomingOpenIssues(ctx context.Context, arg ListIncomingOpenIssuesParams) ([]ListIncomingOpenIssuesRow, error) {
	rows, err := q.db.QueryContext(ctx, listIncomingOpenIssues,
		arg.LastEventID,
		arg.TeamID,
		arg.ProjectID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIncomingOpenIssuesRow{}
	for rows.Next() {
		var i ListIncomingOpenIssuesRow
		if err := rows.Scan(
			&i.Number,
			&i.Title,
			&i.UpdatedAt,
			&i.PeerKey,
			&i.Excerpt,
			&i.Truncated,
			&i.IsNew,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutgoingAnsweredIssues = `-- name: ListOutgoingAnsweredIssues :many
SELECT i.number, i.title, i.updated_at,
       p.key AS peer_key,
       coalesce(left(m.body_md, 500), '')::text AS excerpt,
       coalesce(char_length(m.body_md) > 500, false)::boolean AS truncated,
       EXISTS (
           SELECT 1 FROM events e
           WHERE e.subject_type = 'issue' AND e.subject_id = i.id AND e.id > $1
       ) AS is_new
FROM issues i
JOIN projects p ON p.id = i.project_id AND p.team_id = i.team_id
LEFT JOIN LATERAL (
    SELECT im.body_md FROM issue_messages im
    WHERE im.issue_id = i.id
    ORDER BY im.created_at DESC, im.id DESC
    LIMIT 1
) m ON true
WHERE i.team_id           = $2
  AND i.author_project_id = $3
  AND i.state             = 'answered'
ORDER BY i.updated_at DESC
LIMIT $4::int
`

type ListOutgoingAnsweredIssuesParams struct {
	LastEventID int64     `json:"last_event_id"`
	TeamID      uuid.UUID `json:"team_id"`
	ProjectID   uuid.UUID `json:"project_id"`
	MaxRows     int32     `json:"max_rows"`
}

type ListOutgoingAnsweredIssuesRow struct {
	Number    int64     `json:"number"`
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updated_at"`
	PeerKey   string    `json:"peer_key"`
	Excerpt   string    `json:"excerpt"`
	Truncated bool      `json:"truncated"`
	IsNew     bool      `json:"is_new"`
}

// Seau 2 — answered : j'étais bloqué, je ne le suis plus. Le dernier message est la réponse.
// La ref porte la clé du DESTINATAIRE (p.key), pas la mienne : c'est ce que l'agent doit
// réutiliser dans answer_issue.
func (q *Queries) ListOutgoingAnsweredIssues(ctx context.Context, arg ListOutgoingAnsweredIssuesParams) ([]ListOutgoingAnsweredIssuesRow, error) {
	rows, err := q.db.QueryContext(ctx, listOutgoingAnsweredIssues,
		arg.LastEventID,
		arg.TeamID,
		arg.ProjectID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOutgoingAnsweredIssuesRow{}
	for rows.Next() {
		var i ListOutgoingAnsweredIssuesRow
		if err := rows.Scan(
			&i.Number,
			&i.Title,
			&i.UpdatedAt,
			&i.PeerKey,
			&i.Excerpt,
			&i.Truncated,
			&i.IsNew,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnblockedTasks = `-- name: ListUnblockedTasks :many
SELECT t.number, t.title, t.priority, t.status,
       EXISTS (
           SELECT 1 FROM events e
           WHERE e.subject_type = 'task' AND e.subject_id = t.id AND e.id > $1
       ) AS is_new
FROM (
    SELECT dep.task_id, max(dep.released_at) AS released_at
    FROM task_dependencies dep
    WHERE dep.project_id = $2
      AND dep.released_at IS NOT NULL
    GROUP BY dep.task_id
) d
JOIN tasks t ON t.id = d.task_id AND t.team_id = $3 AND t.project_id = $2
WHERE t.archived_at IS NULL
  AND t.status IN ('todo', 'blocked')
  AND NOT EXISTS (
      SELECT 1 FROM task_dependencies pending
      WHERE pending.task_id = t.id AND pending.released_at IS NULL
  )
ORDER BY d.released_at DESC
LIMIT $4::int
`

type ListUnblockedTasksParams struct {
	LastEventID int64     `json:"last_event_id"`
	ProjectID   uuid.UUID `json:"project_id"`
	TeamID      uuid.UUID `json:"team_id"`
	MaxRows     int32     `json:"max_rows"`
}

type ListUnblockedTasksRow struct {
	Number   int64        `json:"number"`
	Title    string       `json:"title"`
	Priority TaskPriority `json:"priority"`
	Status   TaskStatus   `json:"status"`
	IsNew    bool         `json:"is_new"`
}

// Seau 4 — unblocked : j'étais bloquée par une autre tâche du repo, plus maintenant.
//
// C'est le seau qui répond au manque d'origine : une tâche débloquée qui ne dit rien ne change
// rien. Comme les trois autres, il est recalculé et non rejoué — la trace durable est
// `released_at` sur l'arête, pas un événement à consommer une fois.
//
// Le parcours part des ARÊTES du projet et remonte vers les tâches : un repo a peu d'arêtes et
// beaucoup de tâches, l'inverse scannerait tout le backlog actif à chaque check_inbox.
//
// `status IN ('todo','blocked')` est la condition de sortie du seau : reprendre la tâche
// (in_progress), la finir ou l'archiver l'en retire. `blocked` y reste parce qu'une tâche que
// l'agent avait bloquée LUI-MÊME ne revient pas à `todo` toute seule — on la notifie quand même,
// sinon la notification dépendrait de qui a posé le blocage.
func (q *Queries) ListUnblockedTasks(ctx context.Context, arg ListUnblockedTasksParams) ([]ListUnblockedTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnblockedTasks,
		arg.LastEventID,
		arg.ProjectID,
		arg.TeamID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnblockedTasksRow{}
	for rows.Next() {
		var i ListUnblockedTasksRow
		if err := rows.Scan(
			&i.Number,
			&i.Title,
			&i.Priority,
			&i.Status,
			&i.IsNew,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
