// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issues.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const answerIssue = `-- name: AnswerIssue :one
WITH target AS (
    UPDATE issues i
    SET state = CASE
                    WHEN $1::boolean            THEN 'closed'
                    WHEN i.project_id = $2 THEN 'answered'
                    ELSE                                 'open'
                END::issue_state,
        closed_at  = CASE WHEN $1::boolean THEN now() ELSE i.closed_at END,
        updated_at = now()
    WHERE i.team_id    = $3
      AND i.project_id = $4
      AND i.number     = $5
      AND (i.project_id = $2 OR i.author_project_id = $2)
      AND i.state <> 'closed'
    RETURNING i.id, i.number, i.state
),
appended AS (
    INSERT INTO issue_messages (issue_id, author_project_id, body_md)
    SELECT t.id, $2, $6 FROM target t
    RETURNING issue_id
)
SELECT t.id, t.number, t.state FROM target t
`

type AnswerIssueParams struct {
	Close           bool      `json:"close"`
	ProjectID       uuid.UUID `json:"project_id"`
	TeamID          uuid.UUID `json:"team_id"`
	TargetProjectID uuid.UUID `json:"target_project_id"`
	Number          int64     `json:"number"`
	BodyMd          string    `json:"body_md"`
}

type AnswerIssueRow struct {
	ID     uuid.UUID  `json:"id"`
	Number int64      `json:"number"`
	State  IssueState `json:"state"`
}

// AnswerIssue ajoute un message ET applique la transition d'état en UNE instruction.
//
// Deux statements séparés laisseraient passer ceci : l'appelant poste son message, le
// correspondant ferme l'issue, la transition ne matche plus — le message existe dans une issue
// close, updated_at n'a pas bougé, et l'inbox (dérivée de l'état) ne le montrera jamais. Une
// réponse écrite qui disparaît.
//
// L'état n'est jamais un paramètre : il est calculé depuis QUI parle. Un agent ne peut pas
// mentir sur l'état qu'il produit.
//   - close = true                → closed (les deux participants peuvent fermer, c'est terminal)
//   - message du destinataire     → answered
//   - message de l'auteur         → open (la relance remet le destinataire en dette)
//
// `AND i.state <> 'closed'` est non négociable : sans lui, répondre à une issue fermée la
// ressuscite. `closed_at` n'est jamais écrasé par NULL : un CASE ... ELSE NULL effacerait la
// date de clôture à chaque message.
func (q *Queries) AnswerIssue(ctx context.Context, arg AnswerIssueParams) (AnswerIssueRow, error) {
	row := q.db.QueryRowContext(ctx, answerIssue,
		arg.Close,
		arg.ProjectID,
		arg.TeamID,
		arg.TargetProjectID,
		arg.Number,
		arg.BodyMd,
	)
	var i AnswerIssueRow
	err := row.Scan(&i.ID, &i.Number, &i.State)
	return i, err
}

const appendEvent = `-- name: AppendEvent :exec
INSERT INTO events (team_id, project_id, actor_project_id, kind, subject_type, subject_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type AppendEventParams struct {
	TeamID         uuid.UUID    `json:"team_id"`
	ProjectID      uuid.UUID    `json:"project_id"`
	ActorProjectID uuid.UUID    `json:"actor_project_id"`
	Kind           string       `json:"kind"`
	SubjectType    EventSubject `json:"subject_type"`
	SubjectID      uuid.UUID    `json:"subject_id"`
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) error {
	_, err := q.db.ExecContext(ctx, appendEvent,
		arg.TeamID,
		arg.ProjectID,
		arg.ActorProjectID,
		arg.Kind,
		arg.SubjectType,
		arg.SubjectID,
	)
	return err
}

const appendFirstMessage = `-- name: AppendFirstMessage :one
INSERT INTO issue_messages (issue_id, author_project_id, body_md)
VALUES ($1, $2, $3)
RETURNING id, issue_id, author_project_id, body_md, created_at
`

type AppendFirstMessageParams struct {
	IssueID         uuid.UUID `json:"issue_id"`
	AuthorProjectID uuid.UUID `json:"author_project_id"`
	BodyMd          string    `json:"body_md"`
}

func (q *Queries) AppendFirstMessage(ctx context.Context, arg AppendFirstMessageParams) (IssueMessage, error) {
	row := q.db.QueryRowContext(ctx, appendFirstMessage, arg.IssueID, arg.AuthorProjectID, arg.BodyMd)
	var i IssueMessage
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.AuthorProjectID,
		&i.BodyMd,
		&i.CreatedAt,
	)
	return i, err
}

const createIssue = `-- name: CreateIssue :one

WITH claimed AS (
    UPDATE projects p
    SET next_number = p.next_number + 1
    WHERE p.team_id = $1 AND p.key = $4
    RETURNING p.id AS project_id, (p.next_number - 1)::bigint AS number
)
INSERT INTO issues (team_id, project_id, author_project_id, number, title, state)
SELECT $1, c.project_id, $2, c.number, $3, 'open'
FROM claimed c
RETURNING id, team_id, project_id, author_project_id, number, title, state, created_at, updated_at, closed_at
`

type CreateIssueParams struct {
	TeamID          uuid.UUID `json:"team_id"`
	AuthorProjectID uuid.UUID `json:"author_project_id"`
	Title           string    `json:"title"`
	ToProjectKey    string    `json:"to_project_key"`
}

// Le scope est DANS la query, sans exception. La clause de visibilité canonique est
//
//	team_id = @team_id AND (project_id = @project_id OR author_project_id = @project_id)
//
// où @project_id vient EXCLUSIVEMENT de Principal.ProjectID. `team_id` y figure toujours, même
// s'il est redondant avec le projet : c'est la défense en profondeur si le projet provenait un
// jour d'une mauvaise résolution.
//
// Ni auteur ni destinataire ⇒ zéro ligne, strictement indiscernable d'un numéro inexistant. Il
// n'existe aucun 403 sur une clé d'issue, donc aucun oracle permettant d'énumérer le backlog
// d'un repo frère par answer_issue("CORE-1"), ("CORE-2"), …
// CreateIssue résout le destinataire, réserve son numéro et insère l'issue en UNE instruction.
//
// Une clé inconnue — ou connue mais appartenant à une autre team — ne matche pas la CTE, donc
// l'INSERT ne produit rien ET aucun numéro n'est consommé. C'est ce qui empêche de faire avancer
// le compteur d'un projet tiers en le devinant, et ce qui rend « inexistant » et « hors team »
// indistinguables sans que le code ait à s'en préoccuper.
//
// Cette instruction doit être la PREMIÈRE de sa transaction : c'est la seule prise de verrou de
// ligne longue durée du chemin d'écriture, et il ne doit y en avoir qu'une (cf. ClaimNextNumber).
func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error) {
	row := q.db.QueryRowContext(ctx, createIssue,
		arg.TeamID,
		arg.AuthorProjectID,
		arg.Title,
		arg.ToProjectKey,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ProjectID,
		&i.AuthorProjectID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getIssueByRef = `-- name: GetIssueByRef :one
SELECT i.id, i.team_id, i.project_id, i.author_project_id, i.number, i.title, i.state, i.created_at, i.updated_at, i.closed_at, p.key AS project_key, a.key AS author_project_key
FROM issues i
JOIN projects p ON p.id = i.project_id        AND p.team_id = i.team_id
JOIN projects a ON a.id = i.author_project_id AND a.team_id = i.team_id
WHERE i.team_id = $1
  AND p.key     = $2
  AND i.number  = $3
  AND (i.project_id = $4 OR i.author_project_id = $4)
`

type GetIssueByRefParams struct {
	TeamID          uuid.UUID `json:"team_id"`
	ProjectKey      string    `json:"project_key"`
	Number          int64     `json:"number"`
	CallerProjectID uuid.UUID `json:"caller_project_id"`
}

type GetIssueByRefRow struct {
	ID               uuid.UUID    `json:"id"`
	TeamID           uuid.UUID    `json:"team_id"`
	ProjectID        uuid.UUID    `json:"project_id"`
	AuthorProjectID  uuid.UUID    `json:"author_project_id"`
	Number           int64        `json:"number"`
	Title            string       `json:"title"`
	State            IssueState   `json:"state"`
	CreatedAt        time.Time    `json:"created_at"`
	UpdatedAt        time.Time    `json:"updated_at"`
	ClosedAt         sql.NullTime `json:"closed_at"`
	ProjectKey       string       `json:"project_key"`
	AuthorProjectKey string       `json:"author_project_key"`
}

// GetIssueByRef résout CORE-34 pour un appelant donné. Le projet est désigné par sa CLÉ, jamais
// par un UUID : un agent n'en manipule pas, donc il ne peut pas en injecter un.
func (q *Queries) GetIssueByRef(ctx context.Context, arg GetIssueByRefParams) (GetIssueByRefRow, error) {
	row := q.db.QueryRowContext(ctx, getIssueByRef,
		arg.TeamID,
		arg.ProjectKey,
		arg.Number,
		arg.CallerProjectID,
	)
	var i GetIssueByRefRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ProjectID,
		&i.AuthorProjectID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.ProjectKey,
		&i.AuthorProjectKey,
	)
	return i, err
}

const listIssueMessages = `-- name: ListIssueMessages :many
SELECT m.body_md, m.created_at, ap.key AS author_key
FROM issue_messages m
JOIN issues i    ON i.id  = m.issue_id
JOIN projects ap ON ap.id = m.author_project_id
WHERE i.team_id = $1
  AND i.id      = $2
  AND (i.project_id = $3 OR i.author_project_id = $3)
ORDER BY m.created_at, m.id
`

type ListIssueMessagesParams struct {
	TeamID          uuid.UUID `json:"team_id"`
	IssueID         uuid.UUID `json:"issue_id"`
	CallerProjectID uuid.UUID `json:"caller_project_id"`
}

type ListIssueMessagesRow struct {
	BodyMd    string    `json:"body_md"`
	CreatedAt time.Time `json:"created_at"`
	AuthorKey string    `json:"author_key"`
}

// Le fil est scopé par jointure sur son issue : impossible de lire les messages d'une issue
// qu'on ne voit pas, même en connaissant son identifiant.
func (q *Queries) ListIssueMessages(ctx context.Context, arg ListIssueMessagesParams) ([]ListIssueMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listIssueMessages, arg.TeamID, arg.IssueID, arg.CallerProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssueMessagesRow{}
	for rows.Next() {
		var i ListIssueMessagesRow
		if err := rows.Scan(&i.BodyMd, &i.CreatedAt, &i.AuthorKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssues = `-- name: ListIssues :many
SELECT i.number, i.state, i.title, i.updated_at,
       p.key AS project_key,
       a.key AS author_project_key,
       (i.project_id = $1) AS incoming
FROM issues i
JOIN projects p ON p.id = i.project_id        AND p.team_id = i.team_id
JOIN projects a ON a.id = i.author_project_id AND a.team_id = i.team_id
WHERE i.team_id = $2
  AND (i.project_id = $1 OR i.author_project_id = $1)
  AND (NOT $3::boolean OR i.project_id        = $1)
  AND (NOT $4::boolean OR i.author_project_id = $1)
  AND ($5::issue_state IS NULL OR i.state = $5::issue_state)
  AND ($6::boolean OR i.state <> 'closed')
ORDER BY i.updated_at DESC, i.number DESC
LIMIT $7::int
`

type ListIssuesParams struct {
	ProjectID     uuid.UUID      `json:"project_id"`
	TeamID        uuid.UUID      `json:"team_id"`
	OnlyIncoming  bool           `json:"only_incoming"`
	OnlyOutgoing  bool           `json:"only_outgoing"`
	State         NullIssueState `json:"state"`
	IncludeClosed bool           `json:"include_closed"`
	MaxRows       int32          `json:"max_rows"`
}

type ListIssuesRow struct {
	Number           int64      `json:"number"`
	State            IssueState `json:"state"`
	Title            string     `json:"title"`
	UpdatedAt        time.Time  `json:"updated_at"`
	ProjectKey       string     `json:"project_key"`
	AuthorProjectKey string     `json:"author_project_key"`
	Incoming         bool       `json:"incoming"`
}

// Une seule query pour les trois cas de rôle : trois queries seraient trois occasions de
// re-sécuriser. `role` n'est JAMAIS une autorisation — c'est une restriction posée par-dessus la
// clause de visibilité complète, qui reste inconditionnelle.
// Filtre d'état par sqlc.narg et jamais par une sentinelle ” castée en enum : SQL ne garantit
// aucun court-circuit sur OR, et ”::issue_state lève un 22P02 selon le plan choisi.
func (q *Queries) ListIssues(ctx context.Context, arg ListIssuesParams) ([]ListIssuesRow, error) {
	rows, err := q.db.QueryContext(ctx, listIssues,
		arg.ProjectID,
		arg.TeamID,
		arg.OnlyIncoming,
		arg.OnlyOutgoing,
		arg.State,
		arg.IncludeClosed,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIssuesRow{}
	for rows.Next() {
		var i ListIssuesRow
		if err := rows.Scan(
			&i.Number,
			&i.State,
			&i.Title,
			&i.UpdatedAt,
			&i.ProjectKey,
			&i.AuthorProjectKey,
			&i.Incoming,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
