// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memory.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const chargeProjectMemoryBytes = `-- name: ChargeProjectMemoryBytes :one
UPDATE projects
SET memory_bytes = memory_bytes + $1::bigint
WHERE id      = $2
  AND team_id = $3
  AND memory_bytes + $1::bigint <= $4::bigint
RETURNING memory_bytes
`

type ChargeProjectMemoryBytesParams struct {
	Bytes     int64     `json:"bytes"`
	ProjectID uuid.UUID `json:"project_id"`
	TeamID    uuid.UUID `json:"team_id"`
	Quota     int64     `json:"quota"`
}

// ChargeProjectMemoryBytes debits the memory storage quota. Same shape, same reasons and same
// single-UPDATE atomicity as ChargeProjectNoteBytes (projects.sql): read, compare and write in one
// statement, so two concurrent entries cannot both read the same total and both get through.
//
// A SEPARATE COUNTER from note_bytes, and not a shared one. The two surfaces have different
// lifetimes and different bounds: a note thread is a journal that grows with every session, a
// memory is a small durable index. Sharing a counter would let a chatty journal refuse the very
// decision entry a session needs to write in order to explain itself.
func (q *Queries) ChargeProjectMemoryBytes(ctx context.Context, arg ChargeProjectMemoryBytesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, chargeProjectMemoryBytes,
		arg.Bytes,
		arg.ProjectID,
		arg.TeamID,
		arg.Quota,
	)
	var memory_bytes int64
	err := row.Scan(&memory_bytes)
	return memory_bytes, err
}

const createMemory = `-- name: CreateMemory :one

INSERT INTO memories (team_id, project_id, slug, kind, title, body_md)
SELECT p.team_id, p.id, $1, $2::memory_kind, $3, $4
FROM projects p
WHERE p.id = $5 AND p.team_id = $6
RETURNING id, slug, kind, title, body_md, created_at, updated_at
`

type CreateMemoryParams struct {
	Slug      string     `json:"slug"`
	Kind      MemoryKind `json:"kind"`
	Title     string     `json:"title"`
	BodyMd    string     `json:"body_md"`
	ProjectID uuid.UUID  `json:"project_id"`
	TeamID    uuid.UUID  `json:"team_id"`
}

type CreateMemoryRow struct {
	ID        uuid.UUID  `json:"id"`
	Slug      string     `json:"slug"`
	Kind      MemoryKind `json:"kind"`
	Title     string     `json:"title"`
	BodyMd    string     `json:"body_md"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

// memory — what a repository remembers about itself. M5 (FLWL-7).
//
// SCOPE RULE OF THIS FILE: `team_id` AND `project_id`, on EVERY statement without exception. Same
// rule as tasks.sql, issues.sql and ref.sql — the repository's first scope rule, the one that makes
// another project's row UNFINDABLE rather than merely forbidden.
//
// There is no OverviewMemories and there must never be one. The team-wide read that `overview.sql`
// grants itself over tasks and issues has a justification memories do not share: a supervisor reads
// a debt to act on it. A memory is a repository talking to its own future sessions, and opening it
// to a third party turns a private note into a channel — which is exactly the design the card
// dropped on 2026-08-05.
//
// AN ENTRY IS NEVER UPDATED AND NEVER DELETED. It is SUPERSEDED, which is a write on the OLD row's
// `superseded_by` and an insert of the new one. That is why no UpdateMemory exists here, and why
// adding one would quietly remove the only thing this table offers over a markdown file: the
// ability to answer "why was it like that" as well as "why is it like this".
// CreateMemory inserts an entry.
//
// The insert is fed by a SELECT on `projects`, exactly like CreateTaskNote is fed by one on
// `tasks`: if the pair (project, team) does not exist, no row is produced, nothing is inserted, and
// the caller gets ErrNotFound. The scope is carried by the statement, not by a prior check some
// caller could forget.
func (q *Queries) CreateMemory(ctx context.Context, arg CreateMemoryParams) (CreateMemoryRow, error) {
	row := q.db.QueryRowContext(ctx, createMemory,
		arg.Slug,
		arg.Kind,
		arg.Title,
		arg.BodyMd,
		arg.ProjectID,
		arg.TeamID,
	)
	var i CreateMemoryRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Kind,
		&i.Title,
		&i.BodyMd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMemories = `-- name: ListMemories :many
SELECT m.id, m.slug, m.kind, m.title, m.body_md, m.created_at, m.updated_at,
       -- Both ends of the supersession chain, resolved to SLUGS. An agent never handles a UUID,
       -- and "superseded" without saying BY WHAT would strip the field of the one thing it is for.
       --
       -- coalesce to the empty string, and the cast that goes with it: a bare subquery is NULLABLE,
       -- so sqlc 1.30 types the column ` + "`" + `string` + "`" + ` and every Scan on an entry still in force — that is,
       -- the nominal case — fails on the NULL. Same trap, same fix and same reason as
       -- OverviewLastSeen. Empty means "in force"; no valid slug can be confused with it, since
       -- memories_slug_shape demands at least one character.
       coalesce((SELECT n.slug FROM memories n WHERE n.id = m.superseded_by), '')::text AS superseded_by,
       -- What this entry replaced. The pointer lives on the OLD row, so reading it forward takes a
       -- correlated subquery, and it can name several entries: a rewrite commonly retires more than
       -- one.
       --
       -- string_agg AND NOT an array, and the reason is a hard constraint rather than taste: sqlc
       -- maps ` + "`" + `text[]` + "`" + ` onto ` + "`" + `pq.StringArray` + "`" + `, which would pull github.com/lib/pq into a repository
       -- whose stack is pgx and whose rule is to add no dependency that was not asked for. The comma
       -- is a safe separator HERE and only here — ` + "`" + `memories_slug_shape` + "`" + ` restricts a slug to
       -- [A-Za-z0-9_-], so no slug can ever contain one. Loosen that CHECK and this splits wrong.
       coalesce((SELECT string_agg(o.slug, ',' ORDER BY o.slug)
                 FROM memories o WHERE o.superseded_by = m.id), '')::text AS supersedes,
       (count(*) OVER ())::bigint AS total
FROM memories m
WHERE m.team_id = $1
  AND m.project_id = $2
  AND ($3::boolean OR m.superseded_by IS NULL)
  AND ($4::memory_kind IS NULL OR m.kind = $4::memory_kind)
ORDER BY m.created_at DESC, m.slug
LIMIT $5::int
`

type ListMemoriesParams struct {
	TeamID            uuid.UUID      `json:"team_id"`
	ProjectID         uuid.UUID      `json:"project_id"`
	IncludeSuperseded bool           `json:"include_superseded"`
	Kind              NullMemoryKind `json:"kind"`
	MaxRows           int32          `json:"max_rows"`
}

type ListMemoriesRow struct {
	ID           uuid.UUID  `json:"id"`
	Slug         string     `json:"slug"`
	Kind         MemoryKind `json:"kind"`
	Title        string     `json:"title"`
	BodyMd       string     `json:"body_md"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	SupersededBy string     `json:"superseded_by"`
	Supersedes   string     `json:"supersedes"`
	Total        int64      `json:"total"`
}

// ListMemories returns the entries still in force, most recent first.
//
// `include_superseded` exists because the history is the point of the table, and it is a parameter
// rather than a second query so the two readings can never drift apart. It defaults to false in the
// service: a session picking a repository up wants what is TRUE, not what once was.
//
// The `kind` filter is nullable: sqlc.narg, so "every kind" is expressible without a second query.
//
// Bounded by @max_rows, like every list of this repository. An index of memories that grows without
// limit fills the context of the agent that reads it on startup — which is the one call this
// feature makes on every single session.
func (q *Queries) ListMemories(ctx context.Context, arg ListMemoriesParams) ([]ListMemoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMemories,
		arg.TeamID,
		arg.ProjectID,
		arg.IncludeSuperseded,
		arg.Kind,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMemoriesRow{}
	for rows.Next() {
		var i ListMemoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Kind,
			&i.Title,
			&i.BodyMd,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SupersededBy,
			&i.Supersedes,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const memoryBySlug = `-- name: MemoryBySlug :one
SELECT m.id, m.slug, m.kind, m.title, m.body_md, m.created_at, m.updated_at,
       -- Both ends of the supersession chain, resolved to SLUGS. An agent never handles a UUID,
       -- and "superseded" without saying BY WHAT would strip the field of the one thing it is for.
       --
       -- coalesce to the empty string, and the cast that goes with it: a bare subquery is NULLABLE,
       -- so sqlc 1.30 types the column ` + "`" + `string` + "`" + ` and every Scan on an entry still in force — that is,
       -- the nominal case — fails on the NULL. Same trap, same fix and same reason as
       -- OverviewLastSeen. Empty means "in force"; no valid slug can be confused with it, since
       -- memories_slug_shape demands at least one character.
       coalesce((SELECT n.slug FROM memories n WHERE n.id = m.superseded_by), '')::text AS superseded_by,
       -- What this entry replaced. The pointer lives on the OLD row, so reading it forward takes a
       -- correlated subquery, and it can name several entries: a rewrite commonly retires more than
       -- one.
       --
       -- string_agg AND NOT an array, and the reason is a hard constraint rather than taste: sqlc
       -- maps ` + "`" + `text[]` + "`" + ` onto ` + "`" + `pq.StringArray` + "`" + `, which would pull github.com/lib/pq into a repository
       -- whose stack is pgx and whose rule is to add no dependency that was not asked for. The comma
       -- is a safe separator HERE and only here — ` + "`" + `memories_slug_shape` + "`" + ` restricts a slug to
       -- [A-Za-z0-9_-], so no slug can ever contain one. Loosen that CHECK and this splits wrong.
       coalesce((SELECT string_agg(o.slug, ',' ORDER BY o.slug)
                 FROM memories o WHERE o.superseded_by = m.id), '')::text AS supersedes
FROM memories m
WHERE m.team_id = $1 AND m.project_id = $2 AND m.slug = $3
`

type MemoryBySlugParams struct {
	TeamID    uuid.UUID `json:"team_id"`
	ProjectID uuid.UUID `json:"project_id"`
	Slug      string    `json:"slug"`
}

type MemoryBySlugRow struct {
	ID           uuid.UUID  `json:"id"`
	Slug         string     `json:"slug"`
	Kind         MemoryKind `json:"kind"`
	Title        string     `json:"title"`
	BodyMd       string     `json:"body_md"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	SupersededBy string     `json:"superseded_by"`
	Supersedes   string     `json:"supersedes"`
}

// MemoryBySlug reads one entry of the caller's project.
func (q *Queries) MemoryBySlug(ctx context.Context, arg MemoryBySlugParams) (MemoryBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, memoryBySlug, arg.TeamID, arg.ProjectID, arg.Slug)
	var i MemoryBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Kind,
		&i.Title,
		&i.BodyMd,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SupersededBy,
		&i.Supersedes,
	)
	return i, err
}

const memoryIndex = `-- name: MemoryIndex :many
SELECT slug, kind, title
FROM memories
WHERE team_id = $1
  AND project_id = $2
  AND superseded_by IS NULL
ORDER BY kind, created_at DESC
LIMIT $3::int
`

type MemoryIndexParams struct {
	TeamID    uuid.UUID `json:"team_id"`
	ProjectID uuid.UUID `json:"project_id"`
	MaxRows   int32     `json:"max_rows"`
}

type MemoryIndexRow struct {
	Slug  string     `json:"slug"`
	Kind  MemoryKind `json:"kind"`
	Title string     `json:"title"`
}

// MemoryIndex is what the MCP handshake injects, and it is why the rest of this file is bounded.
//
// Titles only, no bodies: it is paid once per session, in the agent's context, before its first
// message. A body would turn the index into the whole memory and there would be nothing left to
// read on demand.
//
// Entries still in force only. An index listing superseded decisions would teach an agent things
// that stopped being true, which is the exact failure this feature exists to prevent.
func (q *Queries) MemoryIndex(ctx context.Context, arg MemoryIndexParams) ([]MemoryIndexRow, error) {
	rows, err := q.db.QueryContext(ctx, memoryIndex, arg.TeamID, arg.ProjectID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MemoryIndexRow{}
	for rows.Next() {
		var i MemoryIndexRow
		if err := rows.Scan(&i.Slug, &i.Kind, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMemories = `-- name: SearchMemories :many
SELECT m.id, m.slug, m.kind, m.title, m.body_md, m.created_at, m.updated_at,
       -- Both ends of the supersession chain, resolved to SLUGS. An agent never handles a UUID,
       -- and "superseded" without saying BY WHAT would strip the field of the one thing it is for.
       --
       -- coalesce to the empty string, and the cast that goes with it: a bare subquery is NULLABLE,
       -- so sqlc 1.30 types the column ` + "`" + `string` + "`" + ` and every Scan on an entry still in force — that is,
       -- the nominal case — fails on the NULL. Same trap, same fix and same reason as
       -- OverviewLastSeen. Empty means "in force"; no valid slug can be confused with it, since
       -- memories_slug_shape demands at least one character.
       coalesce((SELECT n.slug FROM memories n WHERE n.id = m.superseded_by), '')::text AS superseded_by,
       -- What this entry replaced. The pointer lives on the OLD row, so reading it forward takes a
       -- correlated subquery, and it can name several entries: a rewrite commonly retires more than
       -- one.
       --
       -- string_agg AND NOT an array, and the reason is a hard constraint rather than taste: sqlc
       -- maps ` + "`" + `text[]` + "`" + ` onto ` + "`" + `pq.StringArray` + "`" + `, which would pull github.com/lib/pq into a repository
       -- whose stack is pgx and whose rule is to add no dependency that was not asked for. The comma
       -- is a safe separator HERE and only here — ` + "`" + `memories_slug_shape` + "`" + ` restricts a slug to
       -- [A-Za-z0-9_-], so no slug can ever contain one. Loosen that CHECK and this splits wrong.
       coalesce((SELECT string_agg(o.slug, ',' ORDER BY o.slug)
                 FROM memories o WHERE o.superseded_by = m.id), '')::text AS supersedes,
       ts_rank_cd(m.search, websearch_to_tsquery('english', $1)) AS rank,
       (count(*) OVER ())::bigint AS total
FROM memories m
WHERE m.team_id = $2
  AND m.project_id = $3
  AND ($4::boolean OR m.superseded_by IS NULL)
  AND ($5::memory_kind IS NULL OR m.kind = $5::memory_kind)
  AND m.search @@ websearch_to_tsquery('english', $1)
ORDER BY rank DESC, m.created_at DESC
LIMIT $6::int
`

type SearchMemoriesParams struct {
	Query             string         `json:"query"`
	TeamID            uuid.UUID      `json:"team_id"`
	ProjectID         uuid.UUID      `json:"project_id"`
	IncludeSuperseded bool           `json:"include_superseded"`
	Kind              NullMemoryKind `json:"kind"`
	MaxRows           int32          `json:"max_rows"`
}

type SearchMemoriesRow struct {
	ID           uuid.UUID  `json:"id"`
	Slug         string     `json:"slug"`
	Kind         MemoryKind `json:"kind"`
	Title        string     `json:"title"`
	BodyMd       string     `json:"body_md"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
	SupersededBy string     `json:"superseded_by"`
	Supersedes   string     `json:"supersedes"`
	Rank         float32    `json:"rank"`
	Total        int64      `json:"total"`
}

// SearchMemories ranks the entries matching a query, best first. Postgres FTS, no embedding and no
// model call: the "no AI in the product" rule holds.
//
// websearch_to_tsquery and not plainto_tsquery: it accepts what a human or an agent actually types
// — quoted phrases, OR, negation with a leading dash — and, crucially, it NEVER raises on malformed
// input. `to_tsquery` would turn a stray parenthesis into a 500 on a search box.
//
// ts_rank_cd over ts_rank: it accounts for the distance between the matched terms, so an entry
// whose title carries both words outranks one that mentions them ten paragraphs apart. The weights
// are the ones set by the generated column — title A, body B.
//
// The scope predicates come FIRST and are not negotiable: the GIN index answers the match, the
// project predicate answers who is allowed to see it, and only the second one is a security
// boundary.
func (q *Queries) SearchMemories(ctx context.Context, arg SearchMemoriesParams) ([]SearchMemoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMemories,
		arg.Query,
		arg.TeamID,
		arg.ProjectID,
		arg.IncludeSuperseded,
		arg.Kind,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchMemoriesRow{}
	for rows.Next() {
		var i SearchMemoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Kind,
			&i.Title,
			&i.BodyMd,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SupersededBy,
			&i.Supersedes,
			&i.Rank,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supersedeMemory = `-- name: SupersedeMemory :one
UPDATE memories
SET superseded_by = $1, updated_at = now()
WHERE team_id       = $2
  AND project_id    = $3
  AND id            = $4
  AND superseded_by IS NULL
RETURNING id, slug
`

type SupersedeMemoryParams struct {
	SupersededBy uuid.NullUUID `json:"superseded_by"`
	TeamID       uuid.UUID     `json:"team_id"`
	ProjectID    uuid.UUID     `json:"project_id"`
	ID           uuid.UUID     `json:"id"`
}

type SupersedeMemoryRow struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
}

// SupersedeMemory marks an entry as replaced by another.
//
// Both endpoints are scoped: `id` is the old entry, read under the caller's project, and
// `superseded_by` is the new one — which the composite foreign key `memories_supersedes_fk` already
// forces into the same project. Belt and braces, and deliberately: the key is a schema guarantee
// and the predicate a query guarantee, and this repository's doctrine is that a defence resting on
// a constraint written in another file is not a defence.
//
// `superseded_by IS NULL` in the WHERE makes it a one-way move. Replaying it returns zero rows
// rather than rewriting history: an entry has exactly one successor, and the second attempt is
// either a mistake or a race.
func (q *Queries) SupersedeMemory(ctx context.Context, arg SupersedeMemoryParams) (SupersedeMemoryRow, error) {
	row := q.db.QueryRowContext(ctx, supersedeMemory,
		arg.SupersededBy,
		arg.TeamID,
		arg.ProjectID,
		arg.ID,
	)
	var i SupersedeMemoryRow
	err := row.Scan(&i.ID, &i.Slug)
	return i, err
}
