// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type TokenScope string

const (
	TokenScopeAdmin   TokenScope = "admin"
	TokenScopeProject TokenScope = "project"
)

func (e *TokenScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TokenScope(s)
	case string:
		*e = TokenScope(s)
	default:
		return fmt.Errorf("unsupported scan type for TokenScope: %T", src)
	}
	return nil
}

type NullTokenScope struct {
	TokenScope TokenScope `json:"token_scope"`
	Valid      bool       `json:"valid"` // Valid is true if TokenScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTokenScope) Scan(value interface{}) error {
	if value == nil {
		ns.TokenScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TokenScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTokenScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TokenScope), nil
}

type Project struct {
	ID         uuid.UUID `json:"id"`
	TeamID     uuid.UUID `json:"team_id"`
	Key        string    `json:"key"`
	Name       string    `json:"name"`
	NextNumber int64     `json:"next_number"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Team struct {
	ID        uuid.UUID `json:"id"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Token struct {
	ID         uuid.UUID     `json:"id"`
	TeamID     uuid.NullUUID `json:"team_id"`
	ProjectID  uuid.NullUUID `json:"project_id"`
	Name       string        `json:"name"`
	Prefix     string        `json:"prefix"`
	SecretHash string        `json:"secret_hash"`
	CreatedAt  time.Time     `json:"created_at"`
	LastUsedAt sql.NullTime  `json:"last_used_at"`
	RevokedAt  sql.NullTime  `json:"revoked_at"`
	Scope      TokenScope    `json:"scope"`
}
