// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type EventSubject string

const (
	EventSubjectTask  EventSubject = "task"
	EventSubjectIssue EventSubject = "issue"
)

func (e *EventSubject) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EventSubject(s)
	case string:
		*e = EventSubject(s)
	default:
		return fmt.Errorf("unsupported scan type for EventSubject: %T", src)
	}
	return nil
}

type NullEventSubject struct {
	EventSubject EventSubject `json:"event_subject"`
	Valid        bool         `json:"valid"` // Valid is true if EventSubject is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEventSubject) Scan(value interface{}) error {
	if value == nil {
		ns.EventSubject, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EventSubject.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEventSubject) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EventSubject), nil
}

type IssueState string

const (
	IssueStateOpen     IssueState = "open"
	IssueStateAnswered IssueState = "answered"
	IssueStateClosed   IssueState = "closed"
)

func (e *IssueState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IssueState(s)
	case string:
		*e = IssueState(s)
	default:
		return fmt.Errorf("unsupported scan type for IssueState: %T", src)
	}
	return nil
}

type NullIssueState struct {
	IssueState IssueState `json:"issue_state"`
	Valid      bool       `json:"valid"` // Valid is true if IssueState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIssueState) Scan(value interface{}) error {
	if value == nil {
		ns.IssueState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IssueState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIssueState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IssueState), nil
}

type MemoryKind string

const (
	MemoryKindDecision MemoryKind = "decision"
	MemoryKindLearning MemoryKind = "learning"
	MemoryKindState    MemoryKind = "state"
)

func (e *MemoryKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemoryKind(s)
	case string:
		*e = MemoryKind(s)
	default:
		return fmt.Errorf("unsupported scan type for MemoryKind: %T", src)
	}
	return nil
}

type NullMemoryKind struct {
	MemoryKind MemoryKind `json:"memory_kind"`
	Valid      bool       `json:"valid"` // Valid is true if MemoryKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemoryKind) Scan(value interface{}) error {
	if value == nil {
		ns.MemoryKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemoryKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemoryKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemoryKind), nil
}

type TaskPriority string

const (
	TaskPriorityLow    TaskPriority = "low"
	TaskPriorityNormal TaskPriority = "normal"
	TaskPriorityHigh   TaskPriority = "high"
	TaskPriorityUrgent TaskPriority = "urgent"
)

func (e *TaskPriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskPriority(s)
	case string:
		*e = TaskPriority(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskPriority: %T", src)
	}
	return nil
}

type NullTaskPriority struct {
	TaskPriority TaskPriority `json:"task_priority"`
	Valid        bool         `json:"valid"` // Valid is true if TaskPriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskPriority) Scan(value interface{}) error {
	if value == nil {
		ns.TaskPriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskPriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskPriority), nil
}

type TaskStatus string

const (
	TaskStatusTodo       TaskStatus = "todo"
	TaskStatusInProgress TaskStatus = "in_progress"
	TaskStatusBlocked    TaskStatus = "blocked"
	TaskStatusDone       TaskStatus = "done"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus `json:"task_status"`
	Valid      bool       `json:"valid"` // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

type TokenScope string

const (
	TokenScopeAdmin   TokenScope = "admin"
	TokenScopeProject TokenScope = "project"
)

func (e *TokenScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TokenScope(s)
	case string:
		*e = TokenScope(s)
	default:
		return fmt.Errorf("unsupported scan type for TokenScope: %T", src)
	}
	return nil
}

type NullTokenScope struct {
	TokenScope TokenScope `json:"token_scope"`
	Valid      bool       `json:"valid"` // Valid is true if TokenScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTokenScope) Scan(value interface{}) error {
	if value == nil {
		ns.TokenScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TokenScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTokenScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TokenScope), nil
}

type Event struct {
	ID             int64        `json:"id"`
	TeamID         uuid.UUID    `json:"team_id"`
	ProjectID      uuid.UUID    `json:"project_id"`
	ActorProjectID uuid.UUID    `json:"actor_project_id"`
	Kind           string       `json:"kind"`
	SubjectType    EventSubject `json:"subject_type"`
	SubjectID      uuid.UUID    `json:"subject_id"`
	CreatedAt      time.Time    `json:"created_at"`
}

type Issue struct {
	ID              uuid.UUID    `json:"id"`
	TeamID          uuid.UUID    `json:"team_id"`
	ProjectID       uuid.UUID    `json:"project_id"`
	AuthorProjectID uuid.UUID    `json:"author_project_id"`
	Number          int64        `json:"number"`
	Title           string       `json:"title"`
	State           IssueState   `json:"state"`
	CreatedAt       time.Time    `json:"created_at"`
	UpdatedAt       time.Time    `json:"updated_at"`
	ClosedAt        sql.NullTime `json:"closed_at"`
}

type IssueMessage struct {
	ID              uuid.UUID `json:"id"`
	IssueID         uuid.UUID `json:"issue_id"`
	AuthorProjectID uuid.UUID `json:"author_project_id"`
	BodyMd          string    `json:"body_md"`
	CreatedAt       time.Time `json:"created_at"`
}

type Memory struct {
	ID           uuid.UUID     `json:"id"`
	TeamID       uuid.UUID     `json:"team_id"`
	ProjectID    uuid.UUID     `json:"project_id"`
	Slug         string        `json:"slug"`
	Kind         MemoryKind    `json:"kind"`
	Title        string        `json:"title"`
	BodyMd       string        `json:"body_md"`
	SupersededBy uuid.NullUUID `json:"superseded_by"`
	CreatedAt    time.Time     `json:"created_at"`
	UpdatedAt    time.Time     `json:"updated_at"`
	Search       interface{}   `json:"search"`
}

type Project struct {
	ID          uuid.UUID `json:"id"`
	TeamID      uuid.UUID `json:"team_id"`
	Key         string    `json:"key"`
	Name        string    `json:"name"`
	NextNumber  int64     `json:"next_number"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	NoteBytes   int64     `json:"note_bytes"`
	MemoryBytes int64     `json:"memory_bytes"`
}

type ProjectTrust struct {
	TeamID        uuid.UUID `json:"team_id"`
	FromProjectID uuid.UUID `json:"from_project_id"`
	ToProjectID   uuid.UUID `json:"to_project_id"`
	CreatedAt     time.Time `json:"created_at"`
}

type Task struct {
	ID         uuid.UUID    `json:"id"`
	TeamID     uuid.UUID    `json:"team_id"`
	ProjectID  uuid.UUID    `json:"project_id"`
	Number     int64        `json:"number"`
	Title      string       `json:"title"`
	BodyMd     string       `json:"body_md"`
	Status     TaskStatus   `json:"status"`
	Priority   TaskPriority `json:"priority"`
	Deadline   sql.NullTime `json:"deadline"`
	CreatedAt  time.Time    `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
	ArchivedAt sql.NullTime `json:"archived_at"`
}

type TaskDependency struct {
	ID            uuid.UUID    `json:"id"`
	ProjectID     uuid.UUID    `json:"project_id"`
	TaskID        uuid.UUID    `json:"task_id"`
	BlockerTaskID uuid.UUID    `json:"blocker_task_id"`
	UntilStatus   TaskStatus   `json:"until_status"`
	SetBlocked    bool         `json:"set_blocked"`
	CreatedAt     time.Time    `json:"created_at"`
	ReleasedAt    sql.NullTime `json:"released_at"`
	Origin        string       `json:"origin"`
}

type TaskNote struct {
	ID        uuid.UUID `json:"id"`
	TaskID    uuid.UUID `json:"task_id"`
	BodyMd    string    `json:"body_md"`
	CreatedAt time.Time `json:"created_at"`
}

type Team struct {
	ID        uuid.UUID `json:"id"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Token struct {
	ID         uuid.UUID     `json:"id"`
	TeamID     uuid.NullUUID `json:"team_id"`
	ProjectID  uuid.NullUUID `json:"project_id"`
	Name       string        `json:"name"`
	Prefix     string        `json:"prefix"`
	SecretHash string        `json:"secret_hash"`
	CreatedAt  time.Time     `json:"created_at"`
	LastUsedAt sql.NullTime  `json:"last_used_at"`
	RevokedAt  sql.NullTime  `json:"revoked_at"`
	Scope      TokenScope    `json:"scope"`
}

type TokenCursor struct {
	TokenID     uuid.UUID `json:"token_id"`
	LastEventID int64     `json:"last_event_id"`
	UpdatedAt   time.Time `json:"updated_at"`
}
