// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const claimNextNumber = `-- name: ClaimNextNumber :one
UPDATE projects
SET next_number = next_number + 1,
    updated_at  = now()
WHERE id = $1 AND team_id = $2
RETURNING next_number - 1 AS claimed_number
`

type ClaimNextNumberParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

// ClaimNextNumber réserve le prochain identifiant lisible du projet (FRNT-34).
// Le UPDATE ... RETURNING sérialise les appels concurrents sur la ligne du projet.
func (q *Queries) ClaimNextNumber(ctx context.Context, arg ClaimNextNumberParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, claimNextNumber, arg.ID, arg.TeamID)
	var claimed_number int32
	err := row.Scan(&claimed_number)
	return claimed_number, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (team_id, key, name)
VALUES ($1, $2, $3)
RETURNING id, team_id, key, name, next_number, created_at, updated_at
`

type CreateProjectParams struct {
	TeamID uuid.UUID `json:"team_id"`
	Key    string    `json:"key"`
	Name   string    `json:"name"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.TeamID, arg.Key, arg.Name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Key,
		&i.Name,
		&i.NextNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one

SELECT id, team_id, key, name, next_number, created_at, updated_at FROM projects WHERE id = $1 AND team_id = $2
`

type GetProjectByIDParams struct {
	ID     uuid.UUID `json:"id"`
	TeamID uuid.UUID `json:"team_id"`
}

// Toute lecture est scopée par team_id : le scope fait partie de la query, pas du handler.
func (q *Queries) GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByID, arg.ID, arg.TeamID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Key,
		&i.Name,
		&i.NextNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectByKey = `-- name: GetProjectByKey :one
SELECT id, team_id, key, name, next_number, created_at, updated_at FROM projects WHERE team_id = $1 AND key = $2
`

type GetProjectByKeyParams struct {
	TeamID uuid.UUID `json:"team_id"`
	Key    string    `json:"key"`
}

func (q *Queries) GetProjectByKey(ctx context.Context, arg GetProjectByKeyParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByKey, arg.TeamID, arg.Key)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Key,
		&i.Name,
		&i.NextNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectsByTeam = `-- name: ListProjectsByTeam :many
SELECT id, team_id, key, name, next_number, created_at, updated_at FROM projects WHERE team_id = $1 ORDER BY key
`

func (q *Queries) ListProjectsByTeam(ctx context.Context, teamID uuid.UUID) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Key,
			&i.Name,
			&i.NextNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
