// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const archiveTask = `-- name: ArchiveTask :one
UPDATE tasks
SET archived_at = now(),
    updated_at  = now()
WHERE team_id = $1
  AND project_id = $2
  AND number = $3
  AND archived_at IS NULL
RETURNING id, team_id, project_id, number, title, body_md, status, priority, deadline, created_at, updated_at, archived_at
`

type ArchiveTaskParams struct {
	TeamID    uuid.UUID `json:"team_id"`
	ProjectID uuid.UUID `json:"project_id"`
	Number    int64     `json:"number"`
}

// Rejouer l'archivage remonte ErrNotFound : la query ne cible que les tâches encore actives.
func (q *Queries) ArchiveTask(ctx context.Context, arg ArchiveTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, archiveTask, arg.TeamID, arg.ProjectID, arg.Number)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ProjectID,
		&i.Number,
		&i.Title,
		&i.BodyMd,
		&i.Status,
		&i.Priority,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one

INSERT INTO tasks (team_id, project_id, number, title, body_md, status, priority, deadline)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, team_id, project_id, number, title, body_md, status, priority, deadline, created_at, updated_at, archived_at
`

type CreateTaskParams struct {
	TeamID    uuid.UUID    `json:"team_id"`
	ProjectID uuid.UUID    `json:"project_id"`
	Number    int64        `json:"number"`
	Title     string       `json:"title"`
	BodyMd    string       `json:"body_md"`
	Status    TaskStatus   `json:"status"`
	Priority  TaskPriority `json:"priority"`
	Deadline  sql.NullTime `json:"deadline"`
}

// Toute lecture et toute écriture porte team_id ET project_id : le scope est DANS la query.
// Une tâche d'un autre projet est introuvable, pas seulement interdite — et il n'existe aucune
// query de tâche sans scope, donc aucun appelant ne peut en oublier un.
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.TeamID,
		arg.ProjectID,
		arg.Number,
		arg.Title,
		arg.BodyMd,
		arg.Status,
		arg.Priority,
		arg.Deadline,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ProjectID,
		&i.Number,
		&i.Title,
		&i.BodyMd,
		&i.Status,
		&i.Priority,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createTaskNote = `-- name: CreateTaskNote :one
INSERT INTO task_notes (task_id, body_md)
SELECT t.id, $1
FROM tasks t
WHERE t.team_id = $2
  AND t.project_id = $3
  AND t.number = $4
  AND t.archived_at IS NULL
RETURNING id, task_id, body_md, created_at
`

type CreateTaskNoteParams struct {
	BodyMd    string    `json:"body_md"`
	TeamID    uuid.UUID `json:"team_id"`
	ProjectID uuid.UUID `json:"project_id"`
	Number    int64     `json:"number"`
}

// L'insertion d'une note passe par un SELECT scopé sur la tâche : impossible d'écrire dans le
// fil d'une tâche d'un autre projet, même en connaissant son identifiant.
func (q *Queries) CreateTaskNote(ctx context.Context, arg CreateTaskNoteParams) (TaskNote, error) {
	row := q.db.QueryRowContext(ctx, createTaskNote,
		arg.BodyMd,
		arg.TeamID,
		arg.ProjectID,
		arg.Number,
	)
	var i TaskNote
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.BodyMd,
		&i.CreatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, team_id, project_id, number, title, body_md, status, priority, deadline, created_at, updated_at, archived_at FROM tasks
WHERE team_id = $1 AND project_id = $2 AND number = $3
`

type GetTaskParams struct {
	TeamID    uuid.UUID `json:"team_id"`
	ProjectID uuid.UUID `json:"project_id"`
	Number    int64     `json:"number"`
}

func (q *Queries) GetTask(ctx context.Context, arg GetTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, arg.TeamID, arg.ProjectID, arg.Number)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ProjectID,
		&i.Number,
		&i.Title,
		&i.BodyMd,
		&i.Status,
		&i.Priority,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const listTaskNotes = `-- name: ListTaskNotes :many
SELECT n.id, n.task_id, n.body_md, n.created_at FROM task_notes n
JOIN tasks t ON t.id = n.task_id
WHERE t.team_id = $1
  AND t.project_id = $2
  AND t.number = $3
ORDER BY n.created_at, n.id
`

type ListTaskNotesParams struct {
	TeamID    uuid.UUID `json:"team_id"`
	ProjectID uuid.UUID `json:"project_id"`
	Number    int64     `json:"number"`
}

func (q *Queries) ListTaskNotes(ctx context.Context, arg ListTaskNotesParams) ([]TaskNote, error) {
	rows, err := q.db.QueryContext(ctx, listTaskNotes, arg.TeamID, arg.ProjectID, arg.Number)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskNote{}
	for rows.Next() {
		var i TaskNote
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.BodyMd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasks = `-- name: ListTasks :many
SELECT id, team_id, project_id, number, title, body_md, status, priority, deadline, created_at, updated_at, archived_at FROM tasks
WHERE team_id = $1
  AND project_id = $2
  AND ($3::boolean OR archived_at IS NULL)
  AND ($4::task_status IS NULL OR status = $4::task_status)
ORDER BY number DESC
LIMIT $5::int
`

type ListTasksParams struct {
	TeamID          uuid.UUID      `json:"team_id"`
	ProjectID       uuid.UUID      `json:"project_id"`
	IncludeArchived bool           `json:"include_archived"`
	Status          NullTaskStatus `json:"status"`
	MaxRows         int32          `json:"max_rows"`
}

// ListTasks sert le backlog du projet courant. Les archivées sont exclues par défaut : un agent
// qui demande son travail en cours ne doit pas payer en tokens l'historique du repo.
func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasks,
		arg.TeamID,
		arg.ProjectID,
		arg.IncludeArchived,
		arg.Status,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.ProjectID,
			&i.Number,
			&i.Title,
			&i.BodyMd,
			&i.Status,
			&i.Priority,
			&i.Deadline,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title      = COALESCE($1, title),
    body_md    = COALESCE($2, body_md),
    status     = COALESCE($3::task_status, status),
    priority   = COALESCE($4::task_priority, priority),
    deadline   = CASE
                     WHEN $5::boolean THEN NULL
                     ELSE COALESCE($6, deadline)
                 END,
    updated_at = now()
WHERE team_id = $7
  AND project_id = $8
  AND number = $9
  AND archived_at IS NULL
RETURNING id, team_id, project_id, number, title, body_md, status, priority, deadline, created_at, updated_at, archived_at
`

type UpdateTaskParams struct {
	Title         sql.NullString   `json:"title"`
	BodyMd        sql.NullString   `json:"body_md"`
	Status        NullTaskStatus   `json:"status"`
	Priority      NullTaskPriority `json:"priority"`
	ClearDeadline bool             `json:"clear_deadline"`
	Deadline      sql.NullTime     `json:"deadline"`
	TeamID        uuid.UUID        `json:"team_id"`
	ProjectID     uuid.UUID        `json:"project_id"`
	Number        int64            `json:"number"`
}

// UpdateTask est un patch : un champ absent (NULL) laisse la valeur en place.
// `clear_deadline` existe parce que NULL signifie déjà « ne change pas » — sans ce drapeau, il
// serait impossible d'effacer une échéance.
// Une tâche archivée n'est pas modifiable : la clause archived_at IS NULL la rend introuvable
// pour cette query, ce qui remonte le même ErrNotFound qu'un numéro inexistant.
//
// TRANCHÉ — un patch ne portant QU'UNE NOTE déplace quand même updated_at, et c'est voulu.
// Une note EST une progression : la tâche remonte en tête du seau `in_progress` de check_inbox,
// qui trie par updated_at DESC, donc la session suivante retrouve d'abord ce que la précédente
// a réellement touché en dernier. L'ancien POST /notes ne le déplaçait pas — c'était l'anomalie,
// pas la référence : il laissait une tâche travaillée pendant une heure au fond de la pile.
// Ce qui n'allait pas, c'est que ce changement de comportement soit arrivé sans être décidé.
func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.Title,
		arg.BodyMd,
		arg.Status,
		arg.Priority,
		arg.ClearDeadline,
		arg.Deadline,
		arg.TeamID,
		arg.ProjectID,
		arg.Number,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ProjectID,
		&i.Number,
		&i.Title,
		&i.BodyMd,
		&i.Status,
		&i.Priority,
		&i.Deadline,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
