// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (slug, name)
VALUES ($1, $2)
RETURNING id, slug, name, created_at, updated_at
`

type CreateTeamParams struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (Team, error) {
	row := q.db.QueryRowContext(ctx, createTeam, arg.Slug, arg.Name)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeam = `-- name: DeleteTeam :one
DELETE FROM teams WHERE id = $1 RETURNING id
`

// DeleteTeam removes a team and, by cascade, EVERYTHING that belongs to it. Card FLWL2-20.
//
// NO GUARD, AND THAT IS THE DIFFERENCE WITH DeleteProject. Deleting one repo is refused while a
// SIBLING repo holds a thread with it, because the sibling survives the deletion and would lose its
// own words from its own side. Here nothing survives: `issues` carries a `team_id` and both of its
// foreign keys are composite against `projects (id, team_id)`, so the two ends of every thread are
// inside this team and go with it. There is no party left to be surprised, so there is nobody to
// protect and no refusal to write. The customer deleting a project is deleting all of it, and the
// screen that asks them is where the second thought belongs.
//
// WHAT ACTUALLY GOES. `projects` and `tokens` reference `teams (id) ON DELETE CASCADE` — they are
// the only two tables that name a team directly. Everything else hangs off `projects`, also in
// cascade: tasks and their notes and their dependencies, issues and their messages, events,
// memories, the trust edges, and the cursors that hang off the tokens. One statement, one
// transaction: there is no window in which half a team exists.
//
// RETURNING id IS NOT DECORATION. Without it a delete that matched nothing is indistinguishable
// from one that removed a team, and the caller would answer 204 on a team that never existed. The
// store turns "no row" into ErrNotFound.
func (q *Queries) DeleteTeam(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, deleteTeam, id)
	err := row.Scan(&id)
	return id, err
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, slug, name, created_at, updated_at FROM teams WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamBySlug = `-- name: GetTeamBySlug :one
SELECT id, slug, name, created_at, updated_at FROM teams WHERE slug = $1
`

func (q *Queries) GetTeamBySlug(ctx context.Context, slug string) (Team, error) {
	row := q.db.QueryRowContext(ctx, getTeamBySlug, slug)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTeams = `-- name: ListTeams :many
SELECT id, slug, name, created_at, updated_at FROM teams ORDER BY created_at
`

func (q *Queries) ListTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.QueryContext(ctx, listTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
