// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const countTokens = `-- name: CountTokens :one
SELECT count(*) FROM tokens
`

func (q *Queries) CountTokens(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTokens)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminToken = `-- name: CreateAdminToken :one
INSERT INTO tokens (scope, team_id, project_id, name, prefix, secret_hash)
VALUES ('admin', NULL, NULL, $1, $2, $3)
RETURNING id, team_id, project_id, name, prefix, secret_hash, created_at, last_used_at, revoked_at, scope
`

type CreateAdminTokenParams struct {
	Name       string `json:"name"`
	Prefix     string `json:"prefix"`
	SecretHash string `json:"secret_hash"`
}

func (q *Queries) CreateAdminToken(ctx context.Context, arg CreateAdminTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, createAdminToken, arg.Name, arg.Prefix, arg.SecretHash)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ProjectID,
		&i.Name,
		&i.Prefix,
		&i.SecretHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.Scope,
	)
	return i, err
}

const createProjectToken = `-- name: CreateProjectToken :one
INSERT INTO tokens (scope, team_id, project_id, name, prefix, secret_hash)
VALUES ('project', $1, $2, $3, $4, $5)
RETURNING id, team_id, project_id, name, prefix, secret_hash, created_at, last_used_at, revoked_at, scope
`

type CreateProjectTokenParams struct {
	TeamID     uuid.NullUUID `json:"team_id"`
	ProjectID  uuid.NullUUID `json:"project_id"`
	Name       string        `json:"name"`
	Prefix     string        `json:"prefix"`
	SecretHash string        `json:"secret_hash"`
}

func (q *Queries) CreateProjectToken(ctx context.Context, arg CreateProjectTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, createProjectToken,
		arg.TeamID,
		arg.ProjectID,
		arg.Name,
		arg.Prefix,
		arg.SecretHash,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ProjectID,
		&i.Name,
		&i.Prefix,
		&i.SecretHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.Scope,
	)
	return i, err
}

const getTokenByPrefix = `-- name: GetTokenByPrefix :one
SELECT id, team_id, project_id, name, prefix, secret_hash, created_at, last_used_at, revoked_at, scope FROM tokens WHERE prefix = $1
`

// GetTokenByPrefix filters neither on revoked_at nor on the secret: the service checks both in
// constant time, so that "unknown prefix", "wrong secret" and "revoked token" are indistinguishable
// from the outside.
func (q *Queries) GetTokenByPrefix(ctx context.Context, prefix string) (Token, error) {
	row := q.db.QueryRowContext(ctx, getTokenByPrefix, prefix)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ProjectID,
		&i.Name,
		&i.Prefix,
		&i.SecretHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.Scope,
	)
	return i, err
}

const listProjectTokens = `-- name: ListProjectTokens :many
SELECT id, team_id, project_id, name, prefix, secret_hash, created_at, last_used_at, revoked_at, scope FROM tokens
WHERE scope = 'project' AND team_id = $1 AND project_id = $2
ORDER BY created_at
`

type ListProjectTokensParams struct {
	TeamID    uuid.NullUUID `json:"team_id"`
	ProjectID uuid.NullUUID `json:"project_id"`
}

func (q *Queries) ListProjectTokens(ctx context.Context, arg ListProjectTokensParams) ([]Token, error) {
	rows, err := q.db.QueryContext(ctx, listProjectTokens, arg.TeamID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Token{}
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.ProjectID,
			&i.Name,
			&i.Prefix,
			&i.SecretHash,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAdminTokens = `-- name: RevokeAdminTokens :execrows
UPDATE tokens
SET revoked_at = now()
WHERE scope = 'admin' AND revoked_at IS NULL
`

// RevokeAdminTokens revokes EVERY live administration token at once, which is the first half of a
// rotation.
//
// Revoking is what makes it a rotation rather than a second key cut for the same lock: the token
// being replaced is, by hypothesis, the one that was lost — leaving it live would leave on the
// installation a credential nobody controls any more.
//
// No identifier is named, and none could be: the server only ever kept a hash, so whoever runs the
// rotation has no way to designate the token they are replacing. That is the whole reason this
// query exists.
func (q *Queries) RevokeAdminTokens(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokeAdminTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const revokeProjectToken = `-- name: RevokeProjectToken :one
UPDATE tokens
SET revoked_at = now()
WHERE id = $1 AND team_id = $2 AND scope = 'project' AND revoked_at IS NULL
RETURNING id, team_id, project_id, name, prefix, secret_hash, created_at, last_used_at, revoked_at, scope
`

type RevokeProjectTokenParams struct {
	ID     uuid.UUID     `json:"id"`
	TeamID uuid.NullUUID `json:"team_id"`
}

func (q *Queries) RevokeProjectToken(ctx context.Context, arg RevokeProjectTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, revokeProjectToken, arg.ID, arg.TeamID)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.ProjectID,
		&i.Name,
		&i.Prefix,
		&i.SecretHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.Scope,
	)
	return i, err
}

const touchToken = `-- name: TouchToken :exec
UPDATE tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, touchToken, id)
	return err
}
