// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wake.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const saveWakeWatermark = `-- name: SaveWakeWatermark :exec

INSERT INTO wake_watermarks (team_id, project_id, head)
VALUES ($1, $2, $3)
ON CONFLICT (team_id, project_id) DO UPDATE
SET head       = GREATEST(wake_watermarks.head, EXCLUDED.head),
    updated_at = now()
`

type SaveWakeWatermarkParams struct {
	TeamID    uuid.UUID `json:"team_id"`
	ProjectID uuid.UUID `json:"project_id"`
	Head      int64     `json:"head"`
}

// The wake watermark, persisted (FLWL-90). The probe answers from memory in steady state (D55); these
// two queries touch Postgres only on the two rare paths that must survive a cold engine — reading the
// watermark once when the cache is cold, and writing it when the probe decides on a launch.
// SaveWakeWatermark records the head the probe last decided on for a project, so the re-wake
// suppression survives a spun-down or restarted engine. GREATEST keeps it monotonic: a lagging
// replica or a concurrent probe can never drag the watermark below a head already decided on, so no
// standing work is re-woken by a stale write.
func (q *Queries) SaveWakeWatermark(ctx context.Context, arg SaveWakeWatermarkParams) error {
	_, err := q.db.ExecContext(ctx, saveWakeWatermark, arg.TeamID, arg.ProjectID, arg.Head)
	return err
}

const wakeWatermark = `-- name: WakeWatermark :one
SELECT coalesce((SELECT head FROM wake_watermarks
                 WHERE team_id = $1 AND project_id = $2), 0)::bigint AS head
`

type WakeWatermarkParams struct {
	TeamID    uuid.UUID `json:"team_id"`
	ProjectID uuid.UUID `json:"project_id"`
}

// WakeWatermark reads the durable wake watermark of a project, coalesced to 0 when no decision has
// ever been persisted — exactly the cold-start value the probe expects, so a project the probe has
// never decided on evaluates its standing work once and then goes quiet.
func (q *Queries) WakeWatermark(ctx context.Context, arg WakeWatermarkParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, wakeWatermark, arg.TeamID, arg.ProjectID)
	var head int64
	err := row.Scan(&head)
	return head, err
}
