# Makefile — flowlio-agents
# Development targets (delegated to Claude) versus production targets (humans only).

MIGRATE       ?= migrate
SQLC          ?= sqlc
MIGRATIONS    ?= sql/migrations
SCHEMA_DUMP   ?= sql/schema/schema.sql
PG_CONTAINER  ?= flowlio-postgres
HOSTED_ADDR   ?= :42059

# Loads .env when there is one: DATABASE_URL is then available to the targets below.
ifneq (,$(wildcard .env))
include .env
export
endif

DB_URL_DEV    ?= $(DATABASE_URL)
DB_URL_PROD   ?= $(DATABASE_URL_PROD)

.PHONY: help dev-up dev-down run run-hosted build check lint test test-integration vet sqlc schema sommaire up-dev down-dev up-prod new-migration

# -h suppresses the filename prefix grep adds as soon as it is given more than one file. It is
# given more than one: `include .env` above appends .env to MAKEFILE_LIST, so every line came out as
# `Makefile:target: ## …` and awk read "Makefile" as the target name. Invisible without a .env,
# therefore invisible in CI, and `make help` is the first command a contributor runs.
help: ## List the targets
	@grep -hE '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-16s\033[0m %s\n", $$1, $$2}'

## --- Development ---

dev-up: ## Start Postgres 18 (docker compose)
	docker compose up -d

dev-down: ## Stop Postgres 18
	docker compose down

run: ## Run the API
	go run ./cmd/api

# Hosted mode, the way flowlio-core reaches this engine in development.
#
# ADDR is passed on the recipe line rather than through the environment on purpose: the `include
# .env` above already defines ADDR, and an included value beats an inherited one. A shell
# assignment prefix does not.
#
# ADMIN_TOKEN is never written to .env. Putting it there would fatal every plain `make run`:
# config.go refuses a credential that is configured and ignored, so an admin token without
# MODE=hosted stops the process rather than being silently unused.
run-hosted: ## Run the API in hosted mode on HOSTED_ADDR (needs ADMIN_TOKEN)
	@test -n "$(ADMIN_TOKEN)" || { \
		echo "ADMIN_TOKEN is not set. It is the same secret as flowlio-core's AGENTS_ADMIN_TOKEN,"; \
		echo "under two names. Mint one with: go run ./cmd/api mint-admin-token"; \
		exit 1; }
	MODE=hosted ADDR=$(HOSTED_ADDR) go run ./cmd/api

build: ## Compile everything
	go build ./...

## --- Quality (pass these before calling a task done) ---

check: vet test ## vet + tests

vet: ## go vet
	go vet ./...

test: ## Unit tests (no infrastructure required)
	go test ./...

test-integration: ## Integration tests against the development database
	FLOWLIO_TEST_DATABASE_URL="$(DB_URL_DEV)" go test ./... -count=1

lint: ## golangci-lint + the structural guards
	golangci-lint run ./...
	./scripts/check-cross-feature-imports.sh
	./scripts/check-file-size.sh
	./scripts/check-sommaire.sh
	./scripts/check-trust-in-sql-only.sh
	./scripts/check-overview-scope.sh
	./scripts/check-admin-team-scope.sh
	./scripts/check-seal-source.sh
	./scripts/check-authtest-not-in-production.sh

sommaire: ## Resynchronise the line numbers of the // SOMMAIRE blocks
	./scripts/sync-sommaire-lines.sh

## --- Database ---
## sqlc / up-dev / down-dev / new-migration: delegated to Claude.
## up-prod: HUMANS ONLY.

sqlc: ## Generate internal/database/ from sql/migrations + sql/queries
	$(SQLC) generate

## The \restrict / \unrestrict lines carry a RANDOM token, regenerated by pg_dump 18 on every run:
## without this filter, `make schema` produces a diff even when the schema has not moved, and a
## schema snapshot that always diffs teaches you to ignore schema diffs.
schema: ## Regenerate the readable schema snapshot from the development database
	docker exec $(PG_CONTAINER) pg_dump -U flowlio -d flowlio --schema-only --no-owner --no-privileges \
		| grep -vE '^\\(un)?restrict ' > $(SCHEMA_DUMP)

up-dev: ## Apply the migrations in development
	$(MIGRATE) -path $(MIGRATIONS) -database "$(DB_URL_DEV)" up

down-dev: ## Roll back one migration in development
	$(MIGRATE) -path $(MIGRATIONS) -database "$(DB_URL_DEV)" down 1

new-migration: ## make new-migration name=create_users
	$(MIGRATE) create -ext sql -dir $(MIGRATIONS) -seq $(name)

up-prod: ## Apply the migrations in production — HUMANS ONLY
	$(MIGRATE) -path $(MIGRATIONS) -database "$(DB_URL_PROD)" up
