package store

// SOMMAIRE (lire en premier, sauter directement au bon passage)
//
// | Élément     | Résumé                                                            | Ligne |
// |-------------|-------------------------------------------------------------------|-------|
// | Issue       | An issue as persisted, with the keys of both its projects           | 47    |
// | Message     | A message of the thread, attributed to the project that wrote it    | 71    |
// | Ref         | Names CORE-34 for a given caller, scope included                    | 81    |
// | NewIssue    | Data for opening an issue towards a sibling project                 | 90    |
// | IssueFilter | Criteria for reading the issues a project can see                   | 103   |
// | Answer      | A message to append, and an optional closing                        | 117   |
// | Event       | A journal entry, written along with what produces it                | 128   |
// | Store       | Persistence contract of the issue feature                           | 150   |
// | store       | Implementation backed by the queries generated by sqlc              | 177   |
// | New         | Creates the issue store                                             | 188   |
//
// Fin du sommaire.
// =====================================================================
//
// CONTRACT ONLY — the implementations live in issue.go, message.go, event.go and tx.go.

import (
	"context"
	"database/sql"
	"errors"
	"time"

	"github.com/Coddyum/flowlio-agents/internal/database"
	"github.com/Coddyum/flowlio-agents/internal/pkg/cache"
	"github.com/google/uuid"
)

// ErrNotFound covers "does not exist" and "out of reach" alike — the two cases are deliberately
// indistinguishable. ErrConflict covers constraint violations; ErrCorrupted reports an internal
// inconsistency, which is never the caller's fault.
var (
	ErrNotFound  = errors.New("issue store: not found")
	ErrConflict  = errors.New("issue store: conflict")
	ErrCorrupted = errors.New("issue store: corrupted state")
)

// Issue is a question asked by a project of a sibling project in the same team.
//
// ProjectKey is the RECIPIENT's, which owns the issue and gave it its number: it is therefore the
// one composing the readable reference.
type Issue struct {
	ID               uuid.UUID
	TeamID           uuid.UUID
	ProjectID        uuid.UUID
	AuthorProjectID  uuid.UUID
	Number           int64
	Title            string
	State            string
	ProjectKey       string
	AuthorProjectKey string
	// Incoming is true when the caller is the RECIPIENT. It is computed by the query, which already
	// knows the calling project: deducing it higher up would mean carrying UUIDs into a layer that
	// handles none.
	Incoming  bool
	CreatedAt time.Time
	UpdatedAt time.Time
	ClosedAt  *time.Time
	// Effort is the author's declared rigour tier (internal/pkg/effort), or "" when the issue carries
	// none — a NULL column read back as the empty string, which the receiver folds to standard.
	Effort string
}

// Message is an entry of the thread. The author is a PROJECT, not a person: this is a dialogue
// between two repos.
type Message struct {
	AuthorKey string
	Body      string
	CreatedAt time.Time
}

// Ref names an issue for a given caller.
//
// CallerProjectID comes from the token and is never a request parameter: it is what decides
// visibility. ProjectKey is the recipient's, as read from the reference.
type Ref struct {
	TeamID          uuid.UUID
	CallerProjectID uuid.UUID
	ProjectKey      string
	Number          int64
}

// NewIssue carries the opening of an issue. The recipient is named by its KEY: an agent does not
// handle UUIDs, so it cannot inject one.
type NewIssue struct {
	TeamID          uuid.UUID
	AuthorProjectID uuid.UUID
	ToProjectKey    string
	Title           string
	Body            string
	// Effort is the rigour tier the author declared, or "" for none. Validated by the service before
	// it reaches here; stored as NULL when empty so the CHECK admits it.
	Effort string
}

// IssueFilter describes one read. Role is "", "incoming" or "outgoing"; it narrows the visibility
// clause, it never authorises it.
type IssueFilter struct {
	TeamID    uuid.UUID
	ProjectID uuid.UUID

	Role          string
	State         string
	IncludeClosed bool
	Limit         int32
}

// Answer carries a message to append to the thread and, optionally, the closing.
//
// The resulting state is NOT expressible here: it is computed in the database from the caller's
// role. An agent therefore cannot lie about the state it produces.
type Answer struct {
	Ref   Ref
	Body  string
	Close bool
}

// Event is a journal entry, written in the same transaction as what produces it.
//
// NotifyProjectID is the project the event is meant to wake — the counterparty of the actor, the
// same party the push transport signals. It keys the per-project probe head, so a repo's own writes
// (addressed to the other side) never wake it for nothing.
type Event struct {
	TeamID          uuid.UUID
	ProjectID       uuid.UUID
	ActorProjectID  uuid.UUID
	NotifyProjectID uuid.UUID
	Kind            string
	SubjectID       uuid.UUID
}

// Kinds of events emitted by the feature. In v1 the journal only serves the inbox's "new" flag:
// the reference state stays issues.state.
const (
	KindIssueOpened   = "issue.opened"
	KindIssueAnswered = "issue.answered"
	KindIssueReopened = "issue.reopened"
	KindIssueClosed   = "issue.closed"
)

// Store is the contract consumed by the service.
//
// Every method carries its scope: team, and calling project. No issue read or write takes a bare
// identifier.
type Store interface {
	// WithTx runs fn inside a transaction. The issue, its message and its event are written
	// together or not at all: a lost event is a notification never received.
	WithTx(ctx context.Context, fn func(Store) error) error

	// CreateIssue resolves the recipient by its key, reserves its number and inserts the issue in a
	// single statement. An unknown key, or one from another team, consumes no number.
	CreateIssue(ctx context.Context, in NewIssue) (Issue, error)
	IssueByRef(ctx context.Context, ref Ref) (Issue, error)
	ListIssues(ctx context.Context, filter IssueFilter) ([]Issue, error)

	// Answer appends the message AND applies the state transition in a single statement. Splitting
	// the two would let a message land in an issue closed in the meantime.
	Answer(ctx context.Context, in Answer) (Issue, error)

	AddFirstMessage(ctx context.Context, issueID, authorProjectID uuid.UUID, body string) error

	// ListMessages returns the TAIL of the thread — at most limit messages, in write order — and
	// the total number written. The bound is applied by the QUERY: an issue thread carries full
	// bodies, so slicing it in memory would have left the database, the network and the heap paying
	// for the whole of what the caller does not read.
	ListMessages(ctx context.Context, ref Ref, issueID uuid.UUID, limit int32) ([]Message, int, error)

	AppendEvent(ctx context.Context, event Event) error
}

// store backs the contract with the generated queries. db only serves to open a transaction.
type store struct {
	q  *database.Queries
	db *sql.DB
	// cache carries the in-memory probe head: AppendEvent bumps it so a sleeping sibling can be
	// woken without a query (D55, docs/DESIGN-WAKE.md §3).
	cache cache.Cache
	// inTx marks a store that already carries a transaction, so that WithTx refuses nesting.
	inTx bool
}

// New creates the issue store.
func New(q *database.Queries, db *sql.DB, c cache.Cache) Store {
	return &store{q: q, db: db, cache: c}
}
