package store

// SOMMAIRE (lire en premier, sauter directement au bon passage)
//
// | Élément  | Résumé                                                             | Ligne |
// |----------|--------------------------------------------------------------------|-------|
// | Team     | A team, the unit of tenancy                                          | 37    |
// | Project  | A project, that is a repo, identified by its short key               | 45    |
// | Token      | A project token as persisted, never with the secret in clear        | 54    |
// | TrustEdge  | An edge of the trust graph, in readable keys                        | 69    |
// | Store      | Persistence contract of the workspace feature                       | 77    |
// | store      | Implementation backed by the queries generated by sqlc              | 102   |
// | New        | Creates the workspace store                                         | 107   |
//
// Fin du sommaire.
// =====================================================================
//
// CONTRACT ONLY — the implementations live in team.go, project.go and token.go.

import (
	"errors"
	"time"

	"context"

	"github.com/Coddyum/flowlio-agents/internal/database"
	"github.com/google/uuid"
)

// ErrNotFound reports a missing row; ErrConflict a violated uniqueness constraint.
var (
	ErrNotFound = errors.New("workspace store: not found")
	ErrConflict = errors.New("workspace store: conflict")
)

// Team is the unit of tenancy: everything else belongs to it.
type Team struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	CreatedAt time.Time
}

// Project stands for a repo. Key prefixes the readable identifiers (FRNT-34).
type Project struct {
	ID        uuid.UUID
	TeamID    uuid.UUID
	Key       string
	Name      string
	CreatedAt time.Time
}

// Token is a project token as stored: the secret only exists at creation time, as a hash.
type Token struct {
	ID         uuid.UUID
	TeamID     uuid.UUID
	ProjectID  uuid.UUID
	Name       string
	Prefix     string
	CreatedAt  time.Time
	LastUsedAt time.Time
	Revoked    bool
}

// TrustEdge is an edge of the trust graph, returned in readable KEYS.
//
// Undirected: FirstKey and SecondKey are the two ends of a PAIR, in the database's UUID order and
// therefore with no meaning of direction. No method must ever read "first" as a sender.
type TrustEdge struct {
	FirstKey  string
	SecondKey string
	CreatedAt time.Time
}

// Store is the contract consumed by the service. Every read carries its tenancy scope: a query
// without team_id would be an isolation hole, not an ergonomics oversight.
type Store interface {
	CreateTeam(ctx context.Context, slug, name string) (Team, error)
	TeamByID(ctx context.Context, id uuid.UUID) (Team, error)
	TeamBySlug(ctx context.Context, slug string) (Team, error)
	ListTeams(ctx context.Context) ([]Team, error)

	CreateProject(ctx context.Context, teamID uuid.UUID, key, name string) (Project, error)
	ProjectByID(ctx context.Context, teamID, id uuid.UUID) (Project, error)
	ProjectByKey(ctx context.Context, teamID uuid.UUID, key string) (Project, error)
	ListProjects(ctx context.Context, teamID uuid.UUID) ([]Project, error)

	CreateToken(ctx context.Context, teamID, projectID uuid.UUID, name, prefix, hash string) (Token, error)
	ListTokens(ctx context.Context, teamID, projectID uuid.UUID) ([]Token, error)
	RevokeToken(ctx context.Context, teamID, tokenID uuid.UUID) (Token, error)

	// Trust graph. These three methods DECIDE nothing: the decision is the WHERE predicate of
	// CreateIssue. They only serve human administration, under an admin token. Both projects are
	// named by their KEY and resolved INSIDE the query, under the already-proven team_id — never by
	// a UUID coming from elsewhere.
	AllowTrust(ctx context.Context, teamID uuid.UUID, firstKey, secondKey string) (created bool, err error)
	RevokeTrust(ctx context.Context, teamID uuid.UUID, firstKey, secondKey string) (removed bool, err error)
	ListTrustEdges(ctx context.Context, teamID uuid.UUID) ([]TrustEdge, error)
}

// store backs the contract with the generated queries.
type store struct {
	q *database.Queries
}

// New creates the workspace store.
func New(q *database.Queries) Store {
	return &store{q: q}
}
