package store

// SOMMAIRE (lire en premier, sauter directement au bon passage)
//
// | Élément  | Résumé                                                             | Ligne |
// |----------|--------------------------------------------------------------------|-------|
// | Team     | A team, the unit of tenancy                                          | 39    |
// | Project  | A project, that is a repo, identified by its short key               | 47    |
// | Blocker    | A sibling repo whose threads stand in the way of a deletion         | 57    |
// | ProjectDeletion | What a delete attempt actually did                            | 67    |
// | Token      | A project token as persisted, never with the secret in clear        | 73    |
// | TrustEdge  | An edge of the trust graph, in readable keys                        | 89    |
// | Store      | Persistence contract of the workspace feature                       | 97    |
// | store      | Implementation backed by the queries generated by sqlc              | 136   |
// | New        | Creates the workspace store                                         | 141   |
//
// Fin du sommaire.
// =====================================================================
//
// CONTRACT ONLY — the implementations live in team.go, project.go and token.go.

import (
	"errors"
	"time"

	"context"

	"github.com/Coddyum/flowlio-agents/internal/database"
	"github.com/google/uuid"
)

// ErrNotFound reports a missing row; ErrConflict a violated uniqueness constraint.
var (
	ErrNotFound = errors.New("workspace store: not found")
	ErrConflict = errors.New("workspace store: conflict")
)

// Team is the unit of tenancy: everything else belongs to it.
type Team struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	CreatedAt time.Time
}

// Project stands for a repo. Key prefixes the readable identifiers (FRNT-34).
type Project struct {
	ID        uuid.UUID
	TeamID    uuid.UUID
	Key       string
	Name      string
	CreatedAt time.Time
}

// Blocker is a sibling repo that holds threads with a project, and how many of them. It is what
// stands between that project and its deletion.
type Blocker struct {
	Key     string
	Threads int64
}

// ProjectDeletion is what a delete attempt actually did.
//
// Deleted is READ FROM THE QUERY, never inferred from an empty Blockers. "Nothing blocked it" and
// "it was removed" are two statements, and a caller that deduced the second from the first would
// answer 204 on a delete that silently matched no row.
type ProjectDeletion struct {
	Deleted  bool
	Blockers []Blocker
}

// Token is a project token as stored: the secret only exists at creation time, as a hash.
type Token struct {
	ID         uuid.UUID
	TeamID     uuid.UUID
	ProjectID  uuid.UUID
	Name       string
	Prefix     string
	CreatedAt  time.Time
	LastUsedAt time.Time
	Revoked    bool
}

// TrustEdge is an edge of the trust graph, returned in readable KEYS.
//
// DIRECTED (migration 000013): FromKey is the repo allowed to OPEN a question, ToKey the repo it may
// open it at. The two ends are not interchangeable, and a mutually trusted pair comes back as TWO
// edges. Sorting the two keys, anywhere, would erase the only fact this type exists to carry.
type TrustEdge struct {
	FromKey   string
	ToKey     string
	CreatedAt time.Time
}

// Store is the contract consumed by the service. Every read carries its tenancy scope: a query
// without team_id would be an isolation hole, not an ergonomics oversight.
type Store interface {
	CreateTeam(ctx context.Context, slug, name string) (Team, error)
	TeamByID(ctx context.Context, id uuid.UUID) (Team, error)
	TeamBySlug(ctx context.Context, slug string) (Team, error)
	ListTeams(ctx context.Context) ([]Team, error)
	// DeleteTeam removes a team and everything inside it, in one statement and by cascade: its
	// repos, their backlog, their threads, their tokens and their trust edges. It takes NO
	// blockers argument and reports none, unlike DeleteProject — nothing outside the team is an
	// end of anything inside it, so there is no sibling left to lose its words. A team that is
	// not there yields ErrNotFound, never a silent success.
	DeleteTeam(ctx context.Context, id uuid.UUID) error

	CreateProject(ctx context.Context, teamID uuid.UUID, key, name string) (Project, error)
	ProjectByID(ctx context.Context, teamID, id uuid.UUID) (Project, error)
	ProjectByKey(ctx context.Context, teamID uuid.UUID, key string) (Project, error)
	ListProjects(ctx context.Context, teamID uuid.UUID) ([]Project, error)
	// DeleteProject removes a project, and REFUSES while a sibling repo holds a thread with it.
	// The refusal is not an error: it comes back as a ProjectDeletion whose Deleted is false and
	// whose Blockers name the siblings, because the caller has to be able to say WHO is concerned.
	// A project absent from the team yields ErrNotFound, never a silent success.
	DeleteProject(ctx context.Context, teamID, projectID uuid.UUID) (ProjectDeletion, error)

	CreateToken(ctx context.Context, teamID, projectID uuid.UUID, name, prefix, hash string) (Token, error)
	ListTokens(ctx context.Context, teamID, projectID uuid.UUID) ([]Token, error)
	RevokeToken(ctx context.Context, teamID, tokenID uuid.UUID) (Token, error)

	// Trust graph. These three methods DECIDE nothing: the decision is the WHERE predicate of
	// CreateIssue. They only serve human administration, under an admin token. Both projects are
	// named by their KEY and resolved INSIDE the query, under the already-proven team_id — never by
	// a UUID coming from elsewhere.
	//
	// The edge is DIRECTED: `fromKey` may open a question at `toKey`, and the reciprocal is a
	// separate call. Swapping the two arguments names a different edge, not the same one.
	AllowTrust(ctx context.Context, teamID uuid.UUID, fromKey, toKey string) (created bool, err error)
	RevokeTrust(ctx context.Context, teamID uuid.UUID, fromKey, toKey string) (removed bool, err error)
	ListTrustEdges(ctx context.Context, teamID uuid.UUID) ([]TrustEdge, error)
}

// store backs the contract with the generated queries.
type store struct {
	q *database.Queries
}

// New creates the workspace store.
func New(q *database.Queries) Store {
	return &store{q: q}
}
