package store

// SOMMAIRE (lire en premier, sauter directement au bon passage)
//
// | Élément    | Résumé                                                             | Ligne |
// |------------|--------------------------------------------------------------------|-------|
// | Entry          | One memory entry as persisted, within its project scope          | 65    |
// | Entry.InForce  | Says whether the entry still holds                               | 85    |
// | IndexLine      | One line of the index injected into the MCP handshake            | 88    |
// | Filter         | Criteria for reading or searching a project's memory             | 99    |
// | Store          | Persistence contract of the memory feature                       | 116   |
// | store          | Implementation backed by the queries generated by sqlc            | 153   |
// | New            | Creates the memory store                                          | 162   |
//
// Fin du sommaire.
// =====================================================================
//
// CONTRACT ONLY — the implementations live in memory.go, quota.go and tx.go.

import (
	"context"
	"database/sql"
	"errors"
	"time"

	"github.com/Coddyum/flowlio-agents/internal/database"
	"github.com/google/uuid"
)

// ErrNotFound reports a row that is missing OR out of scope — the two are deliberately
// indistinguishable, so a sibling's slug cannot be probed. ErrConflict covers a slug already taken.
var (
	ErrNotFound      = errors.New("memory store: not found")
	ErrConflict      = errors.New("memory store: conflict")
	ErrQuotaExceeded = errors.New("memory store: project memory quota exceeded")
)

// ProjectMemoryBytesQuota bounds, per project, the cumulative size of the memory entries. 8 MiB.
//
// A SEPARATE, AND MUCH LOWER, BOUND THAN THE NOTE THREAD (64 MiB, see task/store). The two carry
// different things: a note thread is a journal that grows with every session and is read back a
// few entries at a time; the memory is a small durable index that a session reads WHOLE on
// startup. Sharing one counter would let a chatty journal refuse the very decision entry a session
// needs in order to explain itself.
//
// 8 MiB is roughly 4 000 entries at the size a real entry has. The reference system this feature
// copies holds some fifteen after months of daily use, so the bound is three orders of magnitude
// past the observed need — which is what a bound against a runaway loop should be. It stops an
// agent writing in circles; it never arbitrates between a thorough repository and a terse one.
const ProjectMemoryBytesQuota int64 = 8 << 20

// Kinds of entry. Three, and the reason is a measurement rather than a preference: see the head of
// migration 000012.
const (
	// KindDecision answers "why is it like this", and names what it replaces.
	KindDecision = "decision"
	// KindLearning answers "what is going to bite again". A resolved blocker IS a learning.
	KindLearning = "learning"
	// KindState answers "where are we, now".
	KindState = "state"
)

// Entry is one memory entry. TeamID and ProjectID are not decorative: they are the scope key
// carried by every query of this feature.
type Entry struct {
	ID        uuid.UUID
	Slug      string
	Kind      string
	Title     string
	Body      string
	CreatedAt time.Time
	UpdatedAt time.Time

	// SupersededBy is the slug of the entry that replaced this one, empty while it is in force.
	// A slug and not an identifier: nothing above this layer ever handles a UUID.
	SupersededBy string
	// Supersedes lists the slugs this entry replaced. Read forward through a correlated subquery,
	// because the pointer is stored on the OLD row — that direction is what makes an entry
	// self-describing without a second call.
	Supersedes []string
}

// InForce says whether the entry still holds. Kept as a method rather than a stored column: the
// truth is the pointer, and a duplicated flag is one more thing that can disagree with it.
func (e Entry) InForce() bool { return e.SupersededBy == "" }

// IndexLine is one line of the index injected into the MCP handshake: a title, never a body.
type IndexLine struct {
	Slug  string
	Kind  string
	Title string
}

// Filter describes one read of a project's memory.
//
// Query empty means "list"; Query set means "search". One type for both because they answer the
// same question with the same scope and the same bound — two would be two places to forget a
// predicate.
type Filter struct {
	TeamID    uuid.UUID
	ProjectID uuid.UUID

	// Kind restricts to one kind. Empty means every kind.
	Kind string
	// Query is the full-text search expression. Empty means no search.
	Query string
	// IncludeSuperseded brings back the entries that were replaced. False by default: a session
	// picking a repository up wants what is TRUE, not what once was.
	IncludeSuperseded bool

	Limit int32
}

// Store is the contract consumed by the service. Every method carries its tenancy scope: a query
// without (team_id, project_id) would be an isolation hole, not an ergonomics oversight.
type Store interface {
	// WithTx runs fn inside a transaction, on a store that shares it. *sql.DB never travels up to
	// the service: all it ever sees is this interface.
	WithTx(ctx context.Context, fn func(Store) error) error

	// Create inserts an entry. The insert is fed by a scoped SELECT on `projects`, so a pair
	// (team, project) that does not exist produces no row rather than an unscoped write.
	Create(ctx context.Context, teamID, projectID uuid.UUID, slug, kind, title, body string) (Entry, error)

	// BySlug reads one entry of the caller's project.
	BySlug(ctx context.Context, teamID, projectID uuid.UUID, slug string) (Entry, error)

	// List returns the entries matching the filter and the total before the bound. Search and
	// plain listing go through the same method: the filter decides.
	List(ctx context.Context, filter Filter) ([]Entry, int, error)

	// Supersede marks oldSlug as replaced by newSlug. Both are resolved under the caller's project,
	// and the composite foreign key forces them into the same one anyway.
	//
	// A one-way move: an entry already superseded yields ErrNotFound rather than being rewritten.
	Supersede(ctx context.Context, teamID, projectID uuid.UUID, oldSlug, newSlug string) error

	// Index returns titles only, for the MCP handshake. Entries in force only: an index naming
	// superseded decisions teaches an agent things that stopped being true, which is the exact
	// failure this feature exists to prevent.
	Index(ctx context.Context, teamID, projectID uuid.UUID, limit int32) ([]IndexLine, error)

	// ChargeBytes debits the project's memory quota, and yields ErrQuotaExceeded rather than
	// debiting past ProjectMemoryBytesQuota. Read, compare and write are a SINGLE update — split in
	// two, two concurrent entries read the same total and both get through.
	//
	// Called in the SAME transaction as the entry it pays for.
	ChargeBytes(ctx context.Context, teamID, projectID uuid.UUID, bytes int64) error
}

// store backs the contract with the generated queries. db only serves to open a transaction in
// WithTx: no query goes through it directly.
type store struct {
	q  *database.Queries
	db *sql.DB
	// inTx marks a store that already carries a transaction, so WithTx refuses nesting rather than
	// opening a second one on another connection.
	inTx bool
}

// New creates the memory store.
func New(q *database.Queries, db *sql.DB) Store {
	return &store{q: q, db: db}
}
